#!/usr/bin/env python3
"""Convert PCM audio sample files to C header arrays for embedding in SDL3 build."""

import os
import sys

# Map from C array name to PCM file path (relative to Altirra res dir)
SAMPLES = [
    ("audio_disk_spin",           "DiskSpin.pcm"),
    ("audio_track_step",          "trackstep.pcm"),
    ("audio_track_step_2",        "TrackStep2.pcm"),
    ("audio_track_step_3",        "TrackStep3.pcm"),
    ("audio_speaker_click",       "speaker-click.pcm"),
    ("audio_1030relay",           "1030relay.pcm"),
    ("audio_printer_1029_pin",    "printer-1029-pin.pcm"),
    ("audio_printer_1029_platen", "printer-1029-platen.pcm"),
    ("audio_printer_1029_retract","printer-1029-retract.pcm"),
    ("audio_printer_1029_home",   "printer-1029-home.pcm"),
    ("audio_printer_1025_feed",   "printer-1025-feed.pcm"),
    ("audio_printer_1020_headmove",   "printer-1020-headmove.pcm"),
    ("audio_printer_1020_headreverse","printer-1020-headreverse.pcm"),
    ("audio_printer_1020_paperfeed",  "printer-1020-paperfeed.pcm"),
    ("audio_printer_1020_pendown",    "printer-1020-pendown.pcm"),
    ("audio_printer_1020_penup",      "printer-1020-penup.pcm"),
]

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    res_dir = os.path.join(script_dir, "..", "..", "Altirra", "res")
    out_path = os.path.join(script_dir, "audio_samples.h")

    with open(out_path, "w") as f:
        f.write("// Auto-generated by generate_audio_samples.py — do not edit\n")
        f.write("// Embedded PCM audio samples for SDL3 build\n\n")
        f.write("#pragma once\n\n")

        for name, pcm_file in SAMPLES:
            pcm_path = os.path.join(res_dir, pcm_file)
            if not os.path.exists(pcm_path):
                print(f"WARNING: {pcm_path} not found, skipping", file=sys.stderr)
                continue

            with open(pcm_path, "rb") as pf:
                data = pf.read()

            f.write(f"static const unsigned char {name}[] = {{\n")
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
                f.write(f"  {hex_vals},\n")
            f.write(f"}};\n")
            f.write(f"static const unsigned int {name}_len = {len(data)};\n\n")

    print(f"Generated {out_path} with {len(SAMPLES)} samples")

if __name__ == "__main__":
    main()
