#!/usr/bin/env bash
#
# sync_diff.sh — produce the three-way diff reports that drive an
# AltirraSDL upstream sync.
#
# Usage:
#   sync_diff.sh --old <OLD_SNAPSHOT> --new <NEW_SNAPSHOT> --fork <FORK_ROOT>
#
# Output goes to:   syncing-with-upstream/reports/<OLD_LABEL>__to__<NEW_LABEL>/
#
# The script is fully idempotent: rerunning it overwrites the report
# folder for that specific OLD→NEW pair.

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
. "$SCRIPT_DIR/lib/common.sh"

OLD=""
NEW=""
FORK=""

require_value() {
    # $1: flag name, $2: count of remaining args including the flag itself
    [ "$2" -ge 2 ] || fatal "$1 requires a value"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --old)  require_value "$1" "$#"; OLD=$2;  shift 2 ;;
        --new)  require_value "$1" "$#"; NEW=$2;  shift 2 ;;
        --fork) require_value "$1" "$#"; FORK=$2; shift 2 ;;
        -h|--help)
            sed -n '2,20p' "$0"
            exit 0 ;;
        *) fatal "unknown argument: $1" ;;
    esac
done

[ -n "$OLD" ]  || fatal "--old is required"
[ -n "$NEW" ]  || fatal "--new is required"
[ -n "$FORK" ] || fatal "--fork is required"

OLD=$(abs_path "$OLD")
NEW=$(abs_path "$NEW")
FORK=$(abs_path "$FORK")

OLD_LABEL=$(snapshot_label "$OLD")
NEW_LABEL=$(snapshot_label "$NEW")
REPORTS_ROOT=$(cd "$SCRIPT_DIR/.." && pwd -P)/reports
REPORT_DIR=$REPORTS_ROOT/${OLD_LABEL}__to__${NEW_LABEL}

info "OLD  = $OLD   ($OLD_LABEL)"
info "NEW  = $NEW   ($NEW_LABEL)"
info "FORK = $FORK"
info "out  = $REPORT_DIR"

rm -rf "$REPORT_DIR"
mkdir -p "$REPORT_DIR/diffs"

# --- 00: changelog delta -------------------------------------------------
OLD_CHANGES=$OLD/src/Altirra/res/changes.txt
NEW_CHANGES=$NEW/src/Altirra/res/changes.txt
if [ -f "$OLD_CHANGES" ] && [ -f "$NEW_CHANGES" ]; then
    {
        printf 'Changelog delta: %s -> %s\n' "$OLD_LABEL" "$NEW_LABEL"
        printf '%.0s=' $(seq 1 60); printf '\n\n'
        diff -u "$OLD_CHANGES" "$NEW_CHANGES" || true
    } > "$REPORT_DIR/00_changelog.txt"
else
    printf 'changes.txt missing in OLD or NEW\n' > "$REPORT_DIR/00_changelog.txt"
fi

# --- 01/02/03/04/05/06: compute all diff sets via Python (fast) ----------
info "computing diff sets (this may take a few seconds) …"
python3 "$SCRIPT_DIR/lib/compute_diffs.py" \
    --old "$OLD" --new "$NEW" --fork "$FORK" \
    --report-dir "$REPORT_DIR" \
    --trees $SYNC_TREES

# --- 07: per-module classification --------------------------------------
python3 "$SCRIPT_DIR/classify_changes.py" "$REPORT_DIR"

# --- per-file diffs for the three-way bucket ----------------------------
# For each 3-way file we write three diffs:
#   diffs/<safe>.upstream.diff — OLD vs NEW (what upstream changed)
#   diffs/<safe>.fork.diff     — OLD vs FORK (what the fork changed)
#   diffs/<safe>.full.diff     — FORK vs NEW (the combined view)
# The first two are what you need for a three-way merge.
info "writing per-file diffs for three-way files …"
mkdir -p "$REPORT_DIR/diffs"
awk -F'\t' '{print $1}' "$REPORT_DIR/03_three_way.txt" \
    | while IFS= read -r path; do
        [ -z "$path" ] && continue
        safe=${path//\//__}
        if [ -f "$OLD/$path" ] && [ -f "$NEW/$path" ]; then
            diff -u "$OLD/$path"  "$NEW/$path"  > "$REPORT_DIR/diffs/${safe}.upstream.diff" || true
        fi
        if [ -f "$OLD/$path" ] && [ -f "$FORK/$path" ]; then
            diff -u "$OLD/$path"  "$FORK/$path" > "$REPORT_DIR/diffs/${safe}.fork.diff" || true
        fi
        if [ -f "$NEW/$path" ] && [ -f "$FORK/$path" ]; then
            diff -u "$FORK/$path" "$NEW/$path"  > "$REPORT_DIR/diffs/${safe}.full.diff" || true
        fi
    done

# --- SUMMARY -------------------------------------------------------------
count_nonempty() {
    # Count non-empty lines in a file.  Returns 0 for missing files.
    [ -f "$1" ] || { printf 0; return; }
    awk 'NF' "$1" | wc -l | tr -d ' \n'
}
n_upstream=$(count_nonempty "$REPORT_DIR/01_upstream_changed.txt")
n_fork=$(    count_nonempty "$REPORT_DIR/02_fork_changed.txt")
n_three=$(   count_nonempty "$REPORT_DIR/03_three_way.txt")
n_trivial=$( count_nonempty "$REPORT_DIR/04_trivial_copy.txt")
n_added=$(   count_nonempty "$REPORT_DIR/05_added_in_new.txt")
n_removed=$( count_nonempty "$REPORT_DIR/06_removed_in_new.txt")

{
    printf '# Sync report: %s → %s\n\n' "$OLD_LABEL" "$NEW_LABEL"
    printf 'Generated by `tools/sync_diff.sh`.\n\n'
    printf '## Counts\n\n'
    printf '| Bucket                 | Count |\n'
    printf '|------------------------|------:|\n'
    printf '| Upstream changed total | %5d |\n' "$n_upstream"
    printf '|   of which three-way   | %5d |\n' "$n_three"
    printf '|   of which trivial     | %5d |\n' "$n_trivial"
    printf '| Added in NEW           | %5d |\n' "$n_added"
    printf '| Removed in NEW         | %5d |\n' "$n_removed"
    printf '| Fork-modified (info)   | %5d |\n' "$n_fork"
    printf '\n'
    printf '## Next steps\n\n'
    printf '1. Read `00_changelog.txt` — it is the cheapest way to understand intent.\n'
    printf '2. Run `./tools/apply_trivial.py reports/%s__to__%s` to apply trivial copies.\n' "$OLD_LABEL" "$NEW_LABEL"
    printf '3. Resolve three-way files in `07_classified.md` (LLM or by hand).\n'
    printf '4. Mirror user-visible UI changes in `src/AltirraSDL/source/ui/`.\n'
    printf '5. Build and test.\n'
} > "$REPORT_DIR/SUMMARY.md"

info "done. see $REPORT_DIR/SUMMARY.md"
