"""Backward-compatible API for callers using the old single-file asm_writer.

Provides ``emit_xex``, ``emit_segment``, ``emit_header``, ``emit_labels``,
and ``export_xex_to_file`` with the original signatures. These thin
wrappers delegate to the new package internals.
"""

from __future__ import annotations
from typing import Optional, TextIO, TYPE_CHECKING

from .code import strip_inline_address, emit_code_range

if TYPE_CHECKING:
    from ..client import AltirraBridge
    from ..loader import XexImage
    from ..project import Project


def emit_header(out: TextIO, proj: "Project") -> None:
    """Write a banner comment block identifying the project."""
    out.write("; ----------------------------------------------------------\n")
    out.write(f"; MADS source for project: {proj.name}\n")
    if proj.source_path:
        out.write(f"; original binary:        {proj.source_path}\n")
    out.write(";\n")
    out.write("; Generated by altirra_bridge.asm_writer.\n")
    out.write("; ----------------------------------------------------------\n\n")


def emit_labels(out: TextIO, proj: "Project") -> None:
    """Emit ``label = $addr`` equates."""
    if not proj.labels:
        return
    out.write("; --- equates ---\n")
    for addr in sorted(proj.labels):
        out.write(f"{proj.labels[addr]:<16} = ${addr:04x}\n")
    out.write("\n")


def emit_segment(
    out:    TextIO,
    bridge: "AltirraBridge",
    start:  int,
    end:    int,
    proj:   Optional["Project"] = None,
) -> None:
    """Disassemble [start, end] via bridge and write MADS source."""
    from ..project import Project as _P
    proj = proj or _P.new("export")

    out.write(f"\n        org ${start:04x}\n")
    lines = emit_code_range(bridge, start, end, proj.labels, proj.comments)
    for line in lines:
        out.write(line + "\n")


def emit_xex(
    out:    TextIO,
    bridge: "AltirraBridge",
    image:  "XexImage",
    proj:   Optional["Project"] = None,
) -> None:
    """Emit every segment of an XEX image as MADS source.

    This is the legacy single-file API. For the new multi-file
    export use ``write_all()`` instead.
    """
    from ..project import Project as _P
    proj = proj or _P.new("export")
    emit_header(out, proj)
    emit_labels(out, proj)

    for i, seg in enumerate(image.segments):
        out.write(f"\n; --- segment {i}: ${seg.start:04x}-${seg.end:04x} "
                  f"({seg.length} bytes) ---\n")
        emit_segment(out, bridge, seg.start, seg.end, proj)

    out.write("\n; --- entry / init ---\n")
    if image.runad is not None:
        out.write(f"        run ${image.runad:04x}\n")
    for ia in image.initads:
        out.write(f"        ini ${ia:04x}\n")
    out.write("\n; end of file\n")


def export_xex_to_file(
    bridge: "AltirraBridge",
    image:  "XexImage",
    proj:   "Project",
    path:   str,
) -> None:
    """Convenience: write a full XEX disassembly to ``path``."""
    with open(path, "w", encoding="utf-8") as f:
        emit_xex(f, bridge, image, proj)
