"""Top-level orchestration — write_all, write_main, write_segment, verify.

Decides *what* to emit and *where*; delegates formatting to code.py
and data.py.
"""

from __future__ import annotations

import os
import subprocess
from typing import Optional, TYPE_CHECKING

from . import code as _code
from . import data as _data

if TYPE_CHECKING:
    from ..client import AltirraBridge
    from ..loader import XexImage
    from ..project import Project


def write_all(
    bridge: "AltirraBridge",
    image: "XexImage",
    proj: "Project",
    output_dir: str,
    *,
    disasm_unclassified: bool = True,
) -> str:
    """Generate complete MADS source file set.

    Creates ``main.asm``, ``equates.asm``, and per-segment files
    in ``output_dir``. Returns a text summary.

    Loads OS symbols and project labels into the bridge so
    ``DISASM`` output uses standard names. OS symbols are loaded
    first; project labels override them for repurposed addresses.
    """
    os.makedirs(output_dir, exist_ok=True)

    # Load symbols into bridge: OS first, then project (project wins)
    from ..symbols import load_os_symbols
    try:
        load_os_symbols(bridge)
    except Exception:
        pass  # OS symbols are optional
    lab_path = os.path.join(output_dir, "_project.lab")
    proj.export_lab(lab_path)
    try:
        bridge.sym_load(lab_path)
    except Exception:
        pass

    files = []
    files.append(write_equates(image, proj, output_dir))

    for i in range(len(image.segments)):
        files.append(write_segment(bridge, proj, i, image, output_dir))

    files.append(write_main(proj, image, output_dir))

    lines = ["=== MADS Export ==="]
    for f in files:
        lines.append(f"  {f}")
    return "\n".join(lines)


def write_main(
    proj: "Project",
    image: "XexImage",
    output_dir: str,
) -> str:
    """Generate main.asm — master file with ICL + XEX headers.

    Uses ``opt h-`` (raw binary) with ORG bracket notation to emit
    XEX segment headers manually, giving byte-exact control over the
    layout including ``$FFFF`` marker placement.
    """
    xex_name = os.path.basename(proj.source_path or "output.xex")
    ffff_set = set(getattr(image, "ffff_positions", [0]))

    lines = [
        f"; Reconstructed from: {xex_name}",
        f"; Project: {proj.name}",
        "; Generated by altirra_bridge.asm_writer",
        f"; Assemble with: mads main.asm -o:{xex_name}",
        "",
        "    opt h-      ; raw binary — XEX headers via ORG brackets",
        "",
        "    icl 'equates.asm'",
        "",
    ]

    for i, seg in enumerate(image.segments):
        start, end = seg.start, seg.end
        filename = _segment_filename(i, start)

        lines.append(f"; === Segment {i}: ${start:04X}-${end:04X}"
                     f" ({seg.length} bytes) ===")

        if i in ffff_set:
            lines.append(f"    org [a($FFFF),a(${start:04X}),a(${end:04X})],${start:04X}")
        else:
            lines.append(f"    org [a(${start:04X}),a(${end:04X})],${start:04X}")

        lines.append(f"    icl '{filename}'")

        # INI segments (INITAD vectors that fire after this segment)
        # The loader associates initads with segments in load order.
        # For simplicity, attach them to the last data segment.
        lines.append("")

    # Emit INITAD vectors
    for ini_addr in image.initads:
        ini_name = proj.get_label(ini_addr) or f"${ini_addr:04X}"
        lines.append(f"; INI: {ini_name}")
        lines.append("    org [a($02E2),a($02E3)],$02E2")
        lines.append(f"    .word {ini_name}")
        lines.append("")

    # Emit RUNAD
    if image.runad is not None:
        run_name = proj.get_label(image.runad) or f"${image.runad:04X}"
        lines.append("; RUN address")
        lines.append("    org [a($02E0),a($02E1)],$02E0")
        lines.append(f"    .word {run_name}")
        lines.append("")

    # Trailing padding — some XEX files have DOS sector fill after
    # the last segment. Read the original file and emit any bytes
    # past the last parsed segment.
    if proj.source_path and os.path.exists(proj.source_path):
        with open(proj.source_path, "rb") as f:
            raw = f.read()
        # Compute where our parsed segments end in the file
        parsed_size = _compute_parsed_size(raw, image)
        if parsed_size < len(raw):
            padding = raw[parsed_size:]
            lines.append(f"; Trailing padding ({len(padding)} bytes)")
            for j in range(0, len(padding), 16):
                chunk = padding[j:j+16]
                vals = ",".join(f"${b:02X}" for b in chunk)
                lines.append(f"    .byte {vals}")
            lines.append("")

    path = os.path.join(output_dir, "main.asm")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return "main.asm"


def write_equates(
    image: "XexImage",
    proj: "Project",
    output_dir: str,
) -> str:
    """Generate equates.asm — only symbols referenced by the binary.

    Scans segment bytes for operand addresses, collects OS/HW names
    from the official Atari XL OS symbol table, and emits equate
    definitions grouped by category.
    """
    from .._analyzer_tables import OPCODES, HW_READ, HW_WRITE
    from ..symbols import get_os_symbols

    os_syms = get_os_symbols()  # {addr: (name, comment)}

    # Build set of addresses within segments (these become code labels, not equates)
    seg_addrs = set()
    for seg in image.segments:
        for a in range(seg.start, seg.end + 1):
            seg_addrs.add(a)

    # Scan segment bytes for referenced addresses
    referenced = set()
    for seg in image.segments:
        addr = 0
        while addr < len(seg.data):
            opcode = seg.data[addr]
            entry = OPCODES.get(opcode)
            if entry:
                _mnem, mode, size = entry
                if mode in ("abs", "abx", "aby", "ind") and addr + 2 < len(seg.data):
                    target = seg.data[addr + 1] | (seg.data[addr + 2] << 8)
                    referenced.add(target)
                elif mode in ("zp", "zpx", "zpy", "izx", "izy") and addr + 1 < len(seg.data):
                    referenced.add(seg.data[addr + 1])
                addr += size
            else:
                addr += 1

    # Group equates by category
    categories = {
        "zp": ("; Zero page", []),
        "page2": ("; Page 2 — vectors and shadows", []),
        "gtia": ("; GTIA", []),
        "pokey": ("; POKEY", []),
        "pia": ("; PIA", []),
        "antic": ("; ANTIC", []),
        "os": ("; OS ROM entry points", []),
    }
    emitted_names = set()

    for addr in sorted(referenced):
        if addr in seg_addrs:
            continue  # will be a code/data label

        # HW registers — emit both read and write names
        if 0xD000 <= addr <= 0xD01F:
            for name in (HW_READ.get(addr), HW_WRITE.get(addr)):
                if name and name not in emitted_names:
                    categories["gtia"][1].append(f"{name:12s} = ${addr:04X}")
                    emitted_names.add(name)
            continue
        if 0xD200 <= addr <= 0xD20F:
            for name in (HW_READ.get(addr), HW_WRITE.get(addr)):
                if name and name not in emitted_names:
                    categories["pokey"][1].append(f"{name:12s} = ${addr:04X}")
                    emitted_names.add(name)
            continue
        if 0xD300 <= addr <= 0xD303:
            cat = "pia"
        elif 0xD400 <= addr <= 0xD40F:
            for name in (HW_READ.get(addr), HW_WRITE.get(addr)):
                if name and name not in emitted_names:
                    categories["antic"][1].append(f"{name:12s} = ${addr:04X}")
                    emitted_names.add(name)
            continue
        elif addr < 0x100:
            cat = "zp"
        elif 0x200 <= addr < 0x400:
            cat = "page2"
        elif addr >= 0xE400:
            cat = "os"
        else:
            cat = "page2"

        # Look up name: prefer OS symbol table, fall back to HW tables
        os_entry = os_syms.get(addr)
        name = os_entry[0] if os_entry else None
        if not name:
            name = HW_READ.get(addr) or HW_WRITE.get(addr)
        if not name or not name[0].isupper():
            continue
        if name in emitted_names:
            continue

        line = f"{name:12s} = ${addr:04X}"
        # Add OS comment if available
        if os_entry and os_entry[1]:
            line += f"     ; {os_entry[1]}"

        categories[cat][1].append(line)
        emitted_names.add(name)

    # Add ALL base OS symbols that could appear in Altirra's DISASM
    # output (Altirra resolves any address to SYMBOL+offset).
    # Without these equates, MADS would fail on "nop FR1+3" etc.
    for addr, (name, comment) in sorted(os_syms.items()):
        if addr in seg_addrs or name in emitted_names:
            continue
        # Only emit base symbols (not aliases at the same address)
        if 0xD000 <= addr <= 0xD01F:
            cat = "gtia"
        elif 0xD200 <= addr <= 0xD20F:
            cat = "pokey"
        elif 0xD300 <= addr <= 0xD303:
            cat = "pia"
        elif 0xD400 <= addr <= 0xD40F:
            cat = "antic"
        elif addr < 0x100:
            cat = "zp"
        elif 0x200 <= addr < 0x400:
            cat = "page2"
        elif addr >= 0xE400:
            cat = "os"
        else:
            continue  # skip misc ranges
        line = f"{name:12s} = ${addr:04X}"
        if comment:
            line += f"     ; {comment}"
        categories[cat][1].append(line)
        emitted_names.add(name)

    # Project labels outside segments → game variable equates
    game_equates = []
    for addr, name in sorted(proj.labels.items()):
        if addr in seg_addrs or name in emitted_names:
            continue
        line = f"{name:12s} = ${addr:04X}"
        cmt = proj.get_comment(addr)
        if cmt:
            line += f"     ; {cmt}"
        game_equates.append(line)
        emitted_names.add(name)

    # Build output
    out_lines = [
        "; OS and hardware equates — referenced by this program",
        "; Generated by altirra_bridge.asm_writer",
        "",
    ]
    for _cat_key, (header, equates) in categories.items():
        if equates:
            out_lines.append(header)
            out_lines.extend(equates)
            out_lines.append("")
    if game_equates:
        out_lines.append("; Game variables")
        out_lines.extend(game_equates)
        out_lines.append("")

    path = os.path.join(output_dir, "equates.asm")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines) + "\n")
    return "equates.asm"


def write_segment(
    bridge: "AltirraBridge",
    proj: "Project",
    seg_index: int,
    image: "XexImage",
    output_dir: str,
) -> str:
    """Generate one segment source file.

    Builds a region map from ``proj.regions``, then calls
    ``code.emit_mixed()`` to walk the segment respecting code/data
    boundaries.
    """
    seg = image.segments[seg_index]
    start, end = seg.start, seg.end
    filename = _segment_filename(seg_index, start)

    # Header
    lines = [
        f"; =============================================================",
        f"; Segment {seg_index}: ${start:04X}-${end:04X} ({seg.length} bytes)",
        f"; =============================================================",
        "",
        f"    org ${start:04X}",
        "",
    ]

    # Memory accessor for raw bytes — always reads from the XEX file
    # data, NOT from live emulator memory. This ensures data regions
    # and init segments that the game has overwritten at runtime still
    # produce the original bytes.
    class _SegMem:
        def __init__(self, data, base):
            self._data = data
            self._base = base
        def __getitem__(self, addr):
            off = addr - self._base
            if 0 <= off < len(self._data):
                return self._data[off]
            return 0

    mem = _SegMem(seg.data, start)

    # Ensure the XEX segment data is in emulator memory for disasm.
    # Some segments (like init code) are overwritten at runtime by
    # the game. Re-loading from the XEX ensures DISASM sees the
    # original bytes.
    bridge.memload(start, seg.data)

    # Build labels: all project labels for operand resolution,
    # but only emit definitions for labels within this segment.
    all_labels = dict(proj.labels)
    emit_labels = {a: n for a, n in all_labels.items()
                   if start <= a <= end}

    # Build region map
    region_map = _code.build_region_map(proj, start, end)

    # Emit content
    content = _code.emit_mixed(
        bridge, proj, mem, start, end,
        region_map, emit_labels, all_labels)
    lines.append(content)

    path = os.path.join(output_dir, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return filename


def verify(
    proj: "Project",
    output_dir: str,
    mads_path: str = "mads",
) -> str:
    """Assemble with MADS and compare binary output to original XEX.

    Returns a text report: ``"VERIFIED: byte-exact match"`` or a
    mismatch description.
    """
    main_asm = os.path.join(output_dir, "main.asm")
    if not os.path.exists(main_asm):
        return "Error: main.asm not found. Run write_all() first."

    xex_name = os.path.basename(proj.source_path or "output.xex")
    out_xex = os.path.join(output_dir, xex_name)

    try:
        result = subprocess.run(
            [mads_path, "main.asm", f"-o:{xex_name}"],
            capture_output=True, text=True, timeout=30,
            cwd=output_dir,
        )
    except FileNotFoundError:
        return f'Error: MADS not found at "{mads_path}".'
    except subprocess.TimeoutExpired:
        return "Error: MADS assembly timed out."

    if result.returncode != 0:
        return f"Assembly FAILED:\n{result.stdout}\n{result.stderr}"

    if not os.path.exists(out_xex):
        return "Assembly succeeded but output file not found."

    if not proj.source_path or not os.path.exists(proj.source_path):
        return f"Assembly succeeded → {out_xex}\n(Cannot verify: original XEX not available)"

    with open(proj.source_path, "rb") as f:
        original = f.read()
    with open(out_xex, "rb") as f:
        assembled = f.read()

    if original == assembled:
        return f"VERIFIED: byte-exact match ({len(original)} bytes)"

    report = [f"MISMATCH: original={len(original)} assembled={len(assembled)}"]
    for i in range(min(len(original), len(assembled))):
        if original[i] != assembled[i]:
            report.append(f"  First diff at offset ${i:04X}: "
                          f"original=${original[i]:02X} assembled=${assembled[i]:02X}")
            break
    return "\n".join(report)


# --- helpers ---

def _segment_filename(seg_index: int, start_addr: int) -> str:
    return f"seg_{seg_index:02d}_{start_addr:04X}.asm"


def _compute_parsed_size(raw: bytes, image) -> int:
    """Compute how many bytes of the raw XEX file are accounted for
    by the parsed segments + INITAD/RUNAD vectors. The remainder
    is trailing padding."""
    pos = 0
    n = len(raw)
    while pos < n:
        if n - pos < 4:
            break
        w = raw[pos] | (raw[pos + 1] << 8)
        if w == 0xFFFF:
            pos += 2
            continue
        start = w
        end = raw[pos + 2] | (raw[pos + 3] << 8)
        if end < start:
            break  # invalid header — padding starts HERE (before the 4 bytes)
        length = end - start + 1
        pos += 4
        if pos + length > n:
            break
        pos += length
    return pos
