; OS and hardware equates — referenced by this program
; Generated by altirra_bridge.asm_writer

; Zero page
WARMST       = $0008     ; 1-byte warmstart flag (0 = coldstart)
DOSVEC       = $000A     ; 2-byte disk program start vector
DOSINI       = $000C     ; 2-byte disk program initialization address
APPMHI       = $000E     ; 2-byte applications memory high limit
POKMSK       = $0010     ; 1-byte IRQEN shadow
BRKKEY       = $0011     ; 1-byte BREAK key flag (0 = no BREAK)
RTCLOK       = $0012     ; 3-byte real time clock (16 millisecond units)
BUFADR       = $0015     ; 2-byte disk interface buffer address
ICCOMT       = $0017     ; 1-byte CIO command table index
DSKUTL       = $001A     ; 2-byte DOS utility pointer
ABUFPT       = $001C     ; 4-byte ACMI buffer pointer area
ZIOCB        = $0020     ; address of page zero IOCB
ICDNOZ       = $0021     ; 1-byte device number
ICCOMZ       = $0022     ; 1-byte command code
ICSTAZ       = $0023     ; 1-byte status of last action
ICBAHZ       = $0025     ; 1-byte high buffer address
ICPTLZ       = $0026     ; 1-byte low PUT-BYTE routine address-1
ICAX2Z       = $002B     ; 1-byte second auxiliary information
ICSPRZ       = $002C     ; 4-byte spares
CIOCHR       = $002F     ; 1-byte character for current CIO operation
STATUS       = $0030     ; 1-byte SIO operation status
CHKSUM       = $0031     ; 1-byte checksum (single byte sum with carry)
BUFRHI       = $0033     ; 1-byte high data buffer address
BFENLO       = $0034     ; 1-byte low data buffer end address
BFENHI       = $0035     ; 1-byte high data buffer end address
LTEMP        = $0036     ; 2-byte relocating loader temporary
NOCKSM       = $003C     ; 1-byte no checksum follows data flag (0 = does)
BPTR         = $003D     ; 1-byte cassette buffer pointer
FTYPE        = $003E     ; 1-byte cassette IRG type (neg. = continuous)
FEOF         = $003F     ; 1-byte cassette EOF flag (0 = no EOF)
CRITIC       = $0042     ; 1-byte critical section flag (0 = not critical)
FMSZPG       = $0043     ; 7-byte reserved for DOS File Management System
ZCHAIN       = $004A     ; 2-byte handler linkage chain point:
DSTAT        = $004C     ; 1-byte display status
ATRACT       = $004D     ; 1-byte attract-mode timer and flag
DRKMSK       = $004E     ; 1-byte attract-mode dark (luminance) mask
COLRSH       = $004F     ; 1-byte attract-mode color shift
HOLD1        = $0051     ; 1-byte	temporary
RMARGN       = $0053     ; 1-byte text column right margin
ROWCRS       = $0054     ; 1-byte cursor row
COLCRS       = $0055     ; 2-byte cursor column
SAVMSC       = $0058     ; 2-byte saved memory scan counter
OLDCHR       = $005D     ; 1-byte saved character under cursor
OLDADR       = $005E     ; 2-byte saved cursor memory address
FKDEF        = $0060     ; 2-byte function key definition tab:
TOADR        = $0066     ; 2-byte destination address
SAVADR       = $0068     ; 2-byte saved address
RAMTOP       = $006A     ; 1-byte RAM size
BUFCNT       = $006B     ; 1-byte buffer count (logical line size)
BUFSTR       = $006C     ; 2-byte buffer start pointer
BITMSK       = $006E     ; 1-byte bit mask for bit map operation
ROWAC        = $0070     ; 2-byte draw working row
COLAC        = $0072     ; 2-byte draw working column
ENDPT        = $0074     ; 2-byte end point
KEYDEF       = $0079     ; 2-byte key definition table addres:
SWPFLG       = $007B     ; 1-byte split screen swap flag (0 = not swapped)
HOLDCH       = $007C     ; 1-byte temporary character
INSDAT       = $007D     ; 1-byte temporary
COUNTR       = $007E     ; 2-byte draw iteration count
STTIME       = $0080     ; 2-byte main screen timeout timer
STAUT        = $0082     ; 1-byte auto-mode flag
STJMP        = $0083     ; 3-byte ANTIC jump instruction
STCHK        = $008B     ; 2-byte checksum
STSMM        = $008D     ; 1-byte screen memory mask
STPAG        = $0090     ; 2-byte current page to test
STSKP        = $0094     ; 1-byte simulated keypress index
STTMP1       = $0095     ; 2-byte temporary
STADR2       = $00A0     ; 2-byte temporary address
FR0M         = $00D5     ; 5-byte register 0 mantissa
FRE          = $00DA     ; 6-byte (internal) register E
FRX          = $00EC     ; 1-byte temporary
EEXP         = $00ED     ; 1-byte value of exponent
SGNFLG       = $00F0     ; 1-byte sign flag

; Page 2 — vectors and shadows
VDSLST       = $0200     ; 2-byte display list NMI vector
VIMIRQ       = $0216     ; 2-byte immediate IRQ vector
VVBLKI       = $0222     ; 2-byte immediate VBLANK NMI vector
COLDST       = $0244     ; 1-byte coldstart flag (0 = complete)
DDEVIC       = $0300     ; 1-byte unit 1 bus ID

; GTIA
M0PF         = $D000
HPOSP0       = $D000
M1PF         = $D001
HPOSP1       = $D001
M2PF         = $D002
HPOSP2       = $D002
M3PF         = $D003
HPOSP3       = $D003
P0PF         = $D004
HPOSM0       = $D004
P1PF         = $D005
HPOSM1       = $D005
P2PF         = $D006
HPOSM2       = $D006
P3PF         = $D007
HPOSM3       = $D007
M0PL         = $D008
SIZEP0       = $D008
M2PL         = $D00A
SIZEP2       = $D00A
M3PL         = $D00B
SIZEP3       = $D00B
P0PL         = $D00C
SIZEM        = $D00C
P2PL         = $D00E
GRAFP1       = $D00E
P3PL         = $D00F
GRAFP2       = $D00F
TRIG0        = $D010
GRAFP3       = $D010
TRIG1        = $D011
GRAFM        = $D011
TRIG2        = $D012
COLPM0       = $D012
TRIG3        = $D013
COLPM1       = $D013
PAL          = $D014
COLPM2       = $D014
COLPM3       = $D015
COLPF0       = $D016
COLPF1       = $D017
COLPF2       = $D018
COLPF3       = $D019
COLBK        = $D01A
PRIOR        = $D01B
GRACTL       = $D01D
HITCLR       = $D01E
CONSOL       = $D01F
SIZEP1       = $D009     ; player 1 size
P1PL         = $D00D     ; player 1 and player collision
VDELAY       = $D01C     ; vertical delay

; POKEY
POT0         = $D200
AUDF1        = $D200
POT1         = $D201
AUDC1        = $D201
POT2         = $D202
AUDF2        = $D202
POT3         = $D203
AUDC2        = $D203
POT4         = $D204
AUDF3        = $D204
POT5         = $D205
AUDC3        = $D205
POT6         = $D206
AUDF4        = $D206
POT7         = $D207
AUDC4        = $D207
RANDOM       = $D20A
SKRES        = $D20A
IRQST        = $D20E
IRQEN        = $D20E
SKSTAT       = $D20F
SKCTL        = $D20F
AUDCTL       = $D208     ; audio control
STIMER       = $D209     ; start timers
POTGO        = $D20B     ; start potentiometer scan sequence
SEROUT       = $D20D     ; serial port output

; PIA
PORTA        = $D300     ; port A direction register or jacks 0 and 1
PACTL        = $D302     ; port A control
PBCTL        = $D303     ; port B control
PORTB        = $D301     ; port B direction register or memory control

; ANTIC
DMACTL       = $D400
DLISTL       = $D402
DLISTH       = $D403
HSCROL       = $D404
PMBASE       = $D407
CHBASE       = $D409
WSYNC        = $D40A
VCOUNT       = $D40B
NMIEN        = $D40E
CHACTL       = $D401     ; character control
VSCROL       = $D405     ; vertical scroll
PENH         = $D40C     ; light pen horizontal position
PENV         = $D40D     ; light pen vertical position
NMIST        = $D40F     ; NMI interrupt status

; OS ROM entry points
EDITRV       = $E400     ; editor handler vector table
SCRENV       = $E410     ; screen handler vector table
KEYBDV       = $E420     ; keyboard handler vector table
PRINTV       = $E430     ; printer handler vector table
CASETV       = $E440     ; cassette handler vector table
DINITV       = $E450     ; vector to initialize DIO
DSKINV       = $E453     ; vector to DIO
CIOV         = $E456     ; vector to CIO
SIOV         = $E459     ; vector to SIO
SETVBV       = $E45C     ; vector to set VBLANK parameters
SYSVBV       = $E45F     ; vector to process immediate VBLANK NMI
SIOINV       = $E465     ; vector to initialize SIO
SENDEV       = $E468     ; vector to enable SEND
INTINV       = $E46B     ; vector to initialize interrupt handler
CIOINV       = $E46E     ; vector to initialize CIO
BLKBDV       = $E471     ; vector to power-up display (formerly memo pad)
WARMSV       = $E474     ; vector to warmstart
COLDSV       = $E477     ; vector to coldstart
RBLOKV       = $E47A     ; vector to read cassette block
CSOPIV       = $E47D     ; vector to open cassette for input
PUPDIV       = $E480     ; vector to power-up display
SLFTSV       = $E483     ; vector to self-test
PHENTV       = $E486     ; vector to enter peripheral handler
PHUNLV       = $E489     ; vector to unlink peripheral handler
PHINIV       = $E48C     ; vector to initialize peripheral handler
GPDVV        = $E48F     ; generic parallel device handler vector table

; Game variables
temp_ptr_lo  = $0000
temp_ptr_hi  = $0001
sprite_base  = $0002
render_x     = $0004
render_end   = $0005
entity_slot  = $0006
entity_flags = $0007
frame_counter = $0018
joystick_dir = $0019
var_0024     = $0024     ; Unidentified zero-page variable written by the attract handler at $A1BF (ldy #$00; sty $24) and read by state_dispatch at $A1CE (ldx $24; bne loc_A1DC). Runtime values observed: $00 / $48 / $80 during attract, $00 in active player mode — inconsistent with a 0/1/2/3 state machine. The older 'game_state: 0=attract 1=play 2=dying 3=starting' interpretation was wrong (unverifiable in live gameplay). Real play-state variable not yet identified.
dli_status_x = $0027     ; Status-bar sprite HPOS (P3). Written to HPOSP3 at $B752 in the status-bar DLI; also driven from VBI timing code around $B4XX. Not bullet state — the old 'bullet_x' label was wrong.
start_pressed = $0028     ; start_pressed: latched CONSOL START bit, checked in attract mode to leave state 0 and enter state 3 (game starting).
invuln_flags = $0029     ; invuln_flags: post-death invulnerability/respawn flags while game_state=2.
lives_count  = $002A     ; lives_count: remaining player lives. Decremented on death in state 2, initialised in state 3.
bridges_crossed = $002E     ; bridges_crossed: bridge counter. Tracks overall level progression; every bridge crossing awards bonus points and may raise enemy density. Companion to $62.
fuel_drain_ctr = $0032     ; fuel_drain_ctr: fuel drain timer. DEC'd every frame at $AE94; when it wraps it decrements the fuel_level ($76).
fuel_state   = $0038     ; fuel_state: fuel/bullet state byte. Bit 7 set while the player overlaps a fuel depot (refuel active, increments $76 each frame). Also OR'd with $80 on a bullet hit to mark score pending.
bullet_x     = $0039     ; Written to HPOSP1 at $B54F in the playfield DLI each frame. However the P1 DMA buffer ($0D00-$0DFF) is never populated with a bullet bitmap — verified via bridge write-watches and runtime DMA sweep (0 non-zero bytes across thousands of frames including active player mode with fire held). The actual bullet sprite is M1 (packed missile DMA), drawn at $B14B and empirically observed moving upward when fire is held. M1's X comes from HPOSM1 = ($5B>>3)+$5C at $B52C, NOT from $39. The slow inc/dec at $A25B/$A25F oscillates $39 independent of fire input. True role of $39 is not yet characterised; `bullet_x` is a legacy label and the HPOSP1 write appears to be vestigial.
scroll_position = $003A     ; scroll_position: playfield scroll accumulator reset to $0C at $AE86 alongside the fuel/terrain reset path.
fuel_gauge_idx = $003B     ; Fuel-gauge row index. Reset to 0 at $A671/$AF05, read at $AF0F where it's ASL'd and used to index the fuel_gauge_ptrs table at $BAB7 (2-byte pointers) before blitting the next gauge row. Not bullet state — the old 'bullet_state' label was wrong.
entity_timer = $0040
sound_flags  = $0041     ; sound_flags: sound engine request flags, reset to $FF in the fuel/terrain reset path at $AE86.
collision_result = $0050     ; collision_result: per-frame collision result flag, clamped in terrain_bank_update at $A652 and reset to $FF at $AE86.
player_x     = $0052     ; Player horizontal position, river-relative (range roughly $10-$30). Converted to absolute HPOS as player_sprite_x = $52 + $26 + river_width_R at $A4E4. Joystick input updates player_sprite_x directly (inc/dec at $A47F/$A591); $52 tracks separately for river-space logic.
player_sprite_x = $0057     ; Player jet horizontal position. Written to HPOSP2 at $B534 in the playfield DLI — P2 is the jet. Joystick left/right inc/dec this directly at $A47F/$A591. VERIFIED via bridge runtime snapshot: HPOSP2 == $57 in gameplay state.
section_type = $005A     ; section_type: current river section style (straight, narrow, winding). Drives terrain generation.
m1_x_shift_src = $005B     ; Source for HPOSM1 via the playfield DLI formula HPOSM1 = ($5B>>3)+$5C (computed at $B520-$B52C). M1 is the bullet sprite, so $5B/$5C together determine the bullet's X position.
m1_x_base    = $005C     ; Base component of HPOSM1 in the playfield DLI: HPOSM1 = ($5B>>3)+$5C at $B52C. Together with $5B controls the M1 bullet X position. Separate from $39 (which writes HPOSP1 but has no visual effect because P1 has no bitmap).
score_10k    = $0061
score_100    = $0062     ; bridge counter companion to $2E. Both are bumped on bridge crossings to drive scoring and difficulty ramps.
score_high   = $0063     ; score_high: BCD score high byte (hundred-thousands / millions). Updated by the SED/ADC routine at $A547.
score_mid    = $0064     ; score_mid: BCD score mid byte (thousands / ten-thousands). Updated at $A547.
score_low    = $0065     ; score_low: BCD score low byte (ones / tens / hundreds). Updated at $A547.
fuel_level   = $0076     ; fuel_level: current fuel amount, $FF=full to $00=empty. Decremented via fuel_drain_ctr at $32; incremented while the fuel-depot overlap flag $38 bit 7 is set. Reaching $00 kills the player.
player_number = $0077     ; player_number: active player (0 or 1) for two-player alternation. Selects the joystick nibble at $A312 and the COLPM2 value at $B510 ($8E vs $1E).
src_ptr_lo   = $00A1
src_ptr_hi   = $00A2
dst_ptr_lo   = $00A3
dst_ptr_hi   = $00A4
terrain_seed_lo = $00A5     ; terrain_seed_lo: low byte of the terrain PRNG state. Advanced by $A5B7; drives river-bank positions and obstacle layout.
terrain_seed_hi = $00A6     ; terrain_seed_hi: high byte of the terrain PRNG state. Advanced by $A5B7.
pal_flag     = $00BF
frame_ctr_copy = $00C2
sound_timer  = $00C6     ; sound_timer: explosion sound countdown. When non-zero the VBI at $B2A5 plays a noise burst on channel 1 (AUDF1=$40, AUDC1=$AF) and decrements the timer.
cold_start_flag = $00C7
warm_start   = $00CA
scanlines_per_row = $00CB
entity_type_tbl = $0500     ; entity_type[0..5]: 6-slot entity-type table (0=empty, 1-2=ship variants, 3-4=helicopter variants, 5-6=jet variants, 7=fuel depot, $0C=balloon, $0E=bridge). Base of the parallel entity arrays at $0500-$0526.
entity_xpos_tbl = $0516     ; entity_xpos[0..5]: 6-slot entity horizontal-position table. Compared against bullet_x at $A500/$A535 for bullet-hit detection.
entity_size_tbl = $0521     ; entity_size[0..5]: 6-slot entity SIZEP width table. Read by the DLI to set per-scanline SIZEP3 during sprite multiplexing.
XITVBV       = $E462

