; Reconstructed from: river_raid.xex
; Project: river_raid
; Generated by altirra_bridge.asm_writer (reconstructed mode)
; Copy-source ranges are emitted at their runtime addresses
; so project labels/comments line up with the code. The XEX
; layout differs from the original — this is NOT a byte-exact
; round-trip.
; Assemble with: mads main.asm -o:river_raid.xex

    opt h-      ; raw binary — XEX headers via ORG brackets

    icl 'equates.asm'

; === Runtime: $A000-$BFFF — runtime code (copied from $4100-$60FF) ===
    org [a($FFFF),a($A000),a($BFFF)],$A000
    icl 'seg_00_run_A000.asm'

; RUN address
    org [a($02E0),a($02E1)],$02E0
    .word cold_start

