; OS equates — referenced by this program
; Generated by pyA8 reverse engineering toolkit

; Zero page
LNFLG        = $0000
NGFLAG       = $0001
CASINI       = $0002
VCOUNT_START = $0004
TRAMSZ       = $0006
CMCMD        = $0007
WARMST       = $0008
MEMORY_REFRESH_CYCLES = $0009
DOSVEC       = $000A
DOSINI       = $000C
APPMHI       = $000E
POKMSK       = $0010
RTCLOK       = $0012
BUFADR       = $0015
DSKFMS       = $0018
DSKUTL       = $001A
ABUFPT       = $001C
ICHIDZ       = $0020
ICDNOZ       = $0021
ICSTAZ       = $0023
ICBALZ       = $0024
ICBAHZ       = $0025
ICBLHZ       = $0029
ICAX1Z       = $002A
ENTVEC       = $002C
CIOCHR       = $002F
STATUS       = $0030
BUFRLO       = $0032
BUFRHI       = $0033
BFENLO       = $0034
XMTDON       = $003A
CHKSNT       = $003B
NOCKSM       = $003C
FTYPE        = $003E
FEOF         = $003F
FREQ         = $0040
SOUNDR       = $0041
CRITIC       = $0042
DSTAT        = $004C
ATRACT       = $004D
TMPCHR       = $0050
LMARGN       = $0052
SAVMSC       = $0058
OLDROW       = $005A
OLDCHR       = $005D
FKDEF        = $0060
PALNTS       = $0062
LOGCOL       = $0063
TOADR        = $0066
FRMADR       = $0068
BUFSTR       = $006C
BITMSK       = $006E
ENDPT        = $0074
DELTAR       = $0076
HOLDCH       = $007C
COUNTR       = $007E
FRE          = $00DA
FR2          = $00E6
NSIGN        = $00EE
VBI_SCANLINE = $00F8

; Page 2 — vectors and shadows
VDSLST       = $0200
SDMCTL       = $022F
SDLSTL       = $0230
SDLSTH       = $0231
SSKCTL       = $0232
COLDST       = $0244
GPRIOR       = $026F
STICK0       = $0278
STRIG0       = $0284
TXTROW       = $0290
PCOLR0       = $02C0
PCOLR2       = $02C2
PCOLR3       = $02C3
COLOR0       = $02C4
COLOR2       = $02C6
COLOR4       = $02C8
CHBAS        = $02F4
CH           = $02FC
DDEVIC       = $0300
ZFR0         = $DA44

; GTIA (read: collision, write: position/color/control)
M0PF         = $D000
HPOSP0       = $D000
M2PF         = $D002
HPOSP2       = $D002
M3PF         = $D003
HPOSP3       = $D003
P0PF         = $D004
HPOSM0       = $D004
P3PF         = $D007
HPOSM3       = $D007
P0PL         = $D00C
SIZEM        = $D00C
PAL          = $D014
COLPM2       = $D014
COLPF0       = $D016
COLPF1       = $D017
COLPF2       = $D018
COLPF3       = $D019
GRACTL       = $D01D
HITCLR       = $D01E

; POKEY (write: audio, read: random/keyboard)
POT0         = $D200
AUDF1        = $D200
POT1         = $D201
AUDC1        = $D201
POT2         = $D202
AUDF2        = $D202
POT3         = $D203
AUDC2        = $D203
POT4         = $D204
AUDF3        = $D204
POT5         = $D205
AUDC3        = $D205
POT6         = $D206
AUDF4        = $D206
POT7         = $D207
AUDC4        = $D207
ALLPOT       = $D208
AUDCTL       = $D208
RANDOM       = $D20A
SKRES        = $D20A
SKSTAT       = $D20F
SKCTL        = $D20F

; PIA
PACTL        = $D302

; ANTIC (write: DMA/scroll, read: counters)
HSCROL       = $D404
VSCROL       = $D405
PMBASE       = $D407
CHBASE       = $D409
WSYNC        = $D40A
NMIEN        = $D40E

; OS ROM entry points
CIOV         = $E456
SETVBV       = $E45C
XITVBV       = $E462

; Game variables — page $3C ($3Cxx)
entry_point  = $3C0A

; Game variables — page $6E ($6Exx)
map_data     = $6E00

; Game variables — $B000-$B300 ($B000-$B300)
entity_grp1_xpos = $B000
entity_grp1_ypos = $B100
entity_grp1_dir = $B200
entity_grp1_type = $B300
