; Reconstructed from: wizard.xex
; Generated by pyA8 reverse engineering toolkit (reconstructed mode)
; Code at runtime addresses — copy routines eliminated
; Assemble with: mads main.asm -o:wizard.xex

    opt h-      ; raw binary — XEX headers via ORG brackets

    icl 'equates.asm'

; === Runtime segment: $0400-$25FF Runtime code (copied from $1A90-$3C8F) ===
    org [a($FFFF),a($0400),a($25FF)],$0400
    icl 'seg_00_0400.asm'

; === Segment: $3C90-$6DD7 None ===
    org [a($3C90),a($6DD7)],$3C90
    icl 'seg_00_3C90.asm'

; RUN address
    org [a($02E0),a($02E1)],$02E0
    .word $0636
