; OS equates — referenced by this program
; Generated by pyA8 reverse engineering toolkit

; Zero page
LNFLG        = $0000
NGFLAG       = $0001
CASINI       = $0002
PM_DMA_CYCLES = $0005
TRAMSZ       = $0006
CMCMD        = $0007
WARMST       = $0008
MEMORY_REFRESH_CYCLES = $0009
DOSINI       = $000C
APPMHI       = $000E
POKMSK       = $0010
BRKKEY       = $0011
BUFADR       = $0015
ICCOMT       = $0017
DSKFMS       = $0018
DSKUTL       = $001A
ABUFPT       = $001C
ICHIDZ       = $0020
ICDNOZ       = $0021
ICCOMZ       = $0022
ICSTAZ       = $0023
ICBALZ       = $0024
ICBAHZ       = $0025
ICPTLZ       = $0026
ICPTHZ       = $0027
ICBLLZ       = $0028
ICBLHZ       = $0029
ICAX1Z       = $002A
ICAX2Z       = $002B
ENTVEC       = $002C
ICIDNO       = $002E
CIOCHR       = $002F
STATUS       = $0030
CHKSUM       = $0031
BUFRLO       = $0032
BUFRHI       = $0033
BFENLO       = $0034
BFENHI       = $0035
LTEMP        = $0036
BUFRFL       = $0038
RECVDN       = $0039
XMTDON       = $003A
CHKSNT       = $003B
NOCKSM       = $003C
BPTR         = $003D
FTYPE        = $003E
FEOF         = $003F
FREQ         = $0040
SOUNDR       = $0041
CRITIC       = $0042
FMSZPG       = $0043
ZCHAIN       = $004A
DSTAT        = $004C
ATRACT       = $004D
DRKMSK       = $004E
COLRSH       = $004F
TMPCHR       = $0050
HOLD1        = $0051
LMARGN       = $0052
RMARGN       = $0053
ROWCRS       = $0054
COLCRS       = $0055
DINDEX       = $0057
SAVMSC       = $0058
OLDROW       = $005A
OLDCOL       = $005B
OLDCHR       = $005D
OLDADR       = $005E
FKDEF        = $0060
PALNTS       = $0062
LOGCOL       = $0063
ADRESS       = $0064
TOADR        = $0066
FRMADR       = $0068
RAMTOP       = $006A
BUFCNT       = $006B
BUFSTR       = $006C
BITMSK       = $006E
SHFAMT       = $006F
ROWAC        = $0070
ENDPT        = $0074
DELTAR       = $0076
DELTAC       = $0077
KEYDEF       = $0079
SWPFLG       = $007B
HOLDCH       = $007C
INSDAT       = $007D
COUNTR       = $007E
FR0          = $00D4
FR0M         = $00D5
QTEMP        = $00D9
FRE          = $00DA
FR1          = $00E0
FR1M         = $00E1
FR2          = $00E6
FRX          = $00EC
EEXP         = $00ED
NSIGN        = $00EE
ESIGN        = $00EF
FCHFLG       = $00F0
DIGRT        = $00F1
CIX          = $00F2
INBUFF       = $00F3
ZTEMP1       = $00F5
ZTEMP4       = $00F7
VBI_SCANLINE = $00F8
FLPTR        = $00FC
FPTR2        = $00FE

; Page 2 — vectors and shadows
VKEYBD       = $0208
CDTMV4       = $021E
SDMCTL       = $022F
COLOR4       = $02C8
DDEVIC       = $0300
DBUFLO       = $0304
DUNUSE       = $0307
DBYTLO       = $0308
TIMFLG       = $0317
AFP          = $D800
PDIOV        = $D805
PDVV         = $D80D
PLYEVL       = $DD40
EXP          = $DDC0

; GTIA (read: collision, write: position/color/control)
M0PF         = $D000
HPOSP0       = $D000
M1PF         = $D001
HPOSP1       = $D001
M2PF         = $D002
HPOSP2       = $D002
M3PF         = $D003
HPOSP3       = $D003
P0PF         = $D004
HPOSM0       = $D004
P1PF         = $D005
HPOSM1       = $D005
P2PF         = $D006
HPOSM2       = $D006
P3PF         = $D007
HPOSM3       = $D007
M0PL         = $D008
SIZEP0       = $D008
M1PL         = $D009
SIZEP1       = $D009
M2PL         = $D00A
SIZEP2       = $D00A
M3PL         = $D00B
SIZEP3       = $D00B
P0PL         = $D00C
SIZEM        = $D00C
P1PL         = $D00D
GRAFP0       = $D00D
P2PL         = $D00E
GRAFP1       = $D00E
P3PL         = $D00F
GRAFP2       = $D00F
TRIG0        = $D010
GRAFP3       = $D010
TRIG1        = $D011
GRAFM        = $D011
TRIG2        = $D012
COLPM0       = $D012
TRIG3        = $D013
COLPM1       = $D013
PAL          = $D014
COLPM2       = $D014
COLPM3       = $D015
COLPF1       = $D017
COLPF2       = $D018
COLBK        = $D01A
PRIOR        = $D01B
GRACTL       = $D01D
CONSOL       = $D01F

; POKEY (write: audio, read: random/keyboard)
POT0         = $D200
AUDF1        = $D200
POT1         = $D201
AUDC1        = $D201
POT2         = $D202
AUDF2        = $D202
POT3         = $D203
AUDC2        = $D203
POT4         = $D204
AUDF3        = $D204
POT5         = $D205
AUDC3        = $D205
POT6         = $D206
AUDF4        = $D206
POT7         = $D207
AUDC4        = $D207
ALLPOT       = $D208
AUDCTL       = $D208
KBCODE       = $D209
STIMER       = $D209
IRQST        = $D20E
IRQEN        = $D20E
SKSTAT       = $D20F
SKCTL        = $D20F

; PIA
PORTA        = $D300
PORTB        = $D301

; ANTIC (write: DMA/scroll, read: counters)
DMACTL       = $D400
DLISTL       = $D402
DLISTH       = $D403
PMBASE       = $D407
CHBASE       = $D409
WSYNC        = $D40A
VCOUNT       = $D40B
NMIEN        = $D40E

; OS ROM entry points
EDITRV       = $E400
CASETV       = $E440
PUPDIV       = $E480

; Game variables — ZP game workspace ($00xx)
irq_scanline_ctr = $0004     ; IRQ scanline counter (16→0)
current_column = $000A     ; Column iteration index
fps_timer    = $000F     ; FPS countdown (100→0)
buffer_flag  = $0012     ; Double buffer: /bin/bash0 or 0
viewport_first_col = $0071     ; First column (0=PAL, 5=NTSC)
viewport_num_cols = $0072     ; Column count (0=PAL, B=NTSC)

; Game variables — page $C0 ($C0xx)
sin_table    = $C000     ; 256-entry sine lookup

; Game variables — page $C4 ($C4xx)
cos_table    = $C400     ; Cosine / reciprocal table

; Game variables — page $CF ($CFxx)
wall_dist_table = $CF00     ; BSP wall distance thresholds
wall_height_table = $CF40     ; Wall height for distance

; Game variables — page $F8 ($F8xx)
custom_charset = $F800     ; Custom character set (CHBASE=$F8)

; Game variables — page $FF ($FFxx)
sub_FFFF     = $FFFF
