; Reconstructed from: Project-M-2.0.xex
; Generated by pyA8 reverse engineering toolkit
; Assemble with: mads main.asm -o:Project-M-2.0.xex

    opt h-      ; raw binary — XEX headers via ORG brackets

    icl 'equates.asm'

; === Segment 0: $4000-$5894 None ===
    org [a($FFFF),a($4000),a($5894)],$4000
    icl 'seg_00_4000.asm'

; INI: init_routine
    org [a($02E2),a($02E3)],$02E2
    .word init_routine

; === Segment 1: $2800-$2E50 None ===
    org [a($FFFF),a($2800),a($2E50)],$2800
    icl 'seg_01_2800.asm'

; === Segment 2: $2E51-$2F5C None ===
    org [a($2E51),a($2F5C)],$2E51
    icl 'seg_02_2E51.asm'

; === Segment 3: $3082-$30BF None ===
    org [a($3082),a($30BF)],$3082
    icl 'seg_03_3082.asm'

; === Segment 4: $3100-$31BF None ===
    org [a($3100),a($31BF)],$3100
    icl 'seg_04_3100.asm'

; === Segment 5: $3200-$8E94 None ===
    org [a($3200),a($8E94)],$3200
    icl 'seg_05_3200.asm'

; === Segment 6: $8F00-$90FB None ===
    org [a($8F00),a($90FB)],$8F00
    icl 'seg_06_8F00.asm'

; === Segment 7: $9100-$922D None ===
    org [a($9100),a($922D)],$9100
    icl 'seg_07_9100.asm'

; === Segment 8: $9240-$99F8 None ===
    org [a($9240),a($99F8)],$9240
    icl 'seg_08_9240.asm'

; === Segment 9: $9A00-$BFFF None ===
    org [a($9A00),a($BFFF)],$9A00
    icl 'seg_09_9A00.asm'

; RUN address
    org [a($02E0),a($02E1)],$02E0
    .word entry_point
