; OS equates — referenced by this program
; Generated by pyA8 reverse engineering toolkit

; Zero page
LNFLG        = $0000
NGFLAG       = $0001
CASINI       = $0002
VCOUNT_START = $0004
PM_DMA_CYCLES = $0005
TRAMSZ       = $0006
CMCMD        = $0007
WARMST       = $0008
MEMORY_REFRESH_CYCLES = $0009
DOSVEC       = $000A
DOSINI       = $000C
APPMHI       = $000E
POKMSK       = $0010
BRKKEY       = $0011
RTCLOK       = $0012
BUFADR       = $0015
DSKFMS       = $0018
ABUFPT       = $001C
ICHIDZ       = $0020
ICDNOZ       = $0021
ICCOMZ       = $0022
ICSTAZ       = $0023
ICBALZ       = $0024
ICBAHZ       = $0025
ICPTLZ       = $0026
ICPTHZ       = $0027
ICBLLZ       = $0028
ICBLHZ       = $0029
ICAX1Z       = $002A
ICAX2Z       = $002B
ENTVEC       = $002C
ICIDNO       = $002E
CIOCHR       = $002F
STATUS       = $0030
CHKSUM       = $0031
BUFRLO       = $0032
BUFRHI       = $0033
BFENLO       = $0034
BFENHI       = $0035
LTEMP        = $0036
BUFRFL       = $0038
RECVDN       = $0039
XMTDON       = $003A
CHKSNT       = $003B
NOCKSM       = $003C
BPTR         = $003D
FTYPE        = $003E
FEOF         = $003F
FREQ         = $0040
SOUNDR       = $0041
FMSZPG       = $0043
ATRACT       = $004D
COLRSH       = $004F
TMPCHR       = $0050
LMARGN       = $0052
RMARGN       = $0053
ROWCRS       = $0054
COLCRS       = $0055
DINDEX       = $0057
SAVMSC       = $0058
OLDROW       = $005A
OLDCOL       = $005B
OLDCHR       = $005D
FKDEF        = $0060
PALNTS       = $0062
TOADR        = $0066
FRMADR       = $0068
RAMTOP       = $006A
BUFCNT       = $006B
BUFSTR       = $006C
BITMSK       = $006E
SHFAMT       = $006F
ROWAC        = $0070
CYCLES_PER_SCANLINE = $0072
DELTAR       = $0076
DELTAC       = $0077
SWPFLG       = $007B
HOLDCH       = $007C
INSDAT       = $007D
FR0          = $00D4
FR0M         = $00D5
QTEMP        = $00D9
FRE          = $00DA
FR1          = $00E0
FRX          = $00EC
EEXP         = $00ED
NSIGN        = $00EE
ESIGN        = $00EF
FCHFLG       = $00F0
DIGRT        = $00F1
ZTEMP1       = $00F5
ZTEMP4       = $00F7
VBI_SCANLINE = $00F8
ZTEMP3       = $00F9
FLPTR        = $00FC
FPTR2        = $00FE

; Page 2 — vectors and shadows
VDSLST       = $0200
VKEYBD       = $0208
VIMIRQ       = $0216
CDTMV5       = $0220
VVBLKI       = $0222
SDMCTL       = $022F
COLDST       = $0244
GPRIOR       = $026F
PCOLR0       = $02C0
PCOLR1       = $02C1
PCOLR2       = $02C2
PCOLR3       = $02C3
COLOR0       = $02C4
COLOR1       = $02C5
COLOR2       = $02C6
COLOR3       = $02C7
COLOR4       = $02C8
DDEVIC       = $0300
PDVS         = $D1FF

; GTIA (read: collision, write: position/color/control)
M0PF         = $D000
HPOSP0       = $D000
M1PF         = $D001
HPOSP1       = $D001
M2PF         = $D002
HPOSP2       = $D002
M3PF         = $D003
HPOSP3       = $D003
P0PF         = $D004
HPOSM0       = $D004
P1PF         = $D005
HPOSM1       = $D005
P2PF         = $D006
HPOSM2       = $D006
P3PF         = $D007
HPOSM3       = $D007
M0PL         = $D008
SIZEP0       = $D008
M1PL         = $D009
SIZEP1       = $D009
M2PL         = $D00A
SIZEP2       = $D00A
M3PL         = $D00B
SIZEP3       = $D00B
P0PL         = $D00C
SIZEM        = $D00C
TRIG0        = $D010
GRAFP3       = $D010
TRIG2        = $D012
COLPM0       = $D012
TRIG3        = $D013
COLPM1       = $D013
PAL          = $D014
COLPM2       = $D014
COLPM3       = $D015
COLPF0       = $D016
COLPF1       = $D017
COLPF2       = $D018
COLPF3       = $D019
COLBK        = $D01A
PRIOR        = $D01B
GRACTL       = $D01D
CONSOL       = $D01F

; POKEY (write: audio, read: random/keyboard)
POT0         = $D200
AUDF1        = $D200
POT1         = $D201
AUDC1        = $D201
POT2         = $D202
AUDF2        = $D202
POT3         = $D203
AUDC2        = $D203
POT4         = $D204
AUDF3        = $D204
POT5         = $D205
AUDC3        = $D205
POT6         = $D206
AUDF4        = $D206
POT7         = $D207
AUDC4        = $D207
ALLPOT       = $D208
AUDCTL       = $D208
KBCODE       = $D209
STIMER       = $D209
RANDOM       = $D20A
SKRES        = $D20A
IRQST        = $D20E
IRQEN        = $D20E
SKSTAT       = $D20F
SKCTL        = $D20F

; PIA
PORTA        = $D300

; ANTIC (write: DMA/scroll, read: counters)
DMACTL       = $D400
DLISTL       = $D402
DLISTH       = $D403
PMBASE       = $D407
CHBASE       = $D409
WSYNC        = $D40A
VCOUNT       = $D40B
NMIEN        = $D40E

; Game variables — ZP game workspace ($00xx)
zp_ptr_lo    = $0080     ; General pointer lo — screen row addr during pixel write, direction table during transform
zp_ptr_hi    = $0081     ; General pointer hi
zp_column_x  = $0082     ; Current column X position — saved by STX $82 in rasterize inner loop
zp_proj_x_hi = $0083     ; Projected X high byte (from project_x)
zp_depth_accum = $0084     ; Depth interpolation accumulator — averaged with edge samples in rasterize loop
zp_proj_y_hi = $0085     ; Projected Y high byte (from project_x Y phase)
zp_color_shade = $0086     ; Color/shade interpolation value — terrain color gradient during edge walk
zp_grid_x    = $0088     ; Terrain grid X component — combined with $8A for heightmap index
zp_grid_row  = $008A     ; Terrain grid row — upper nibble used for height buffer indexing
zp_cam_alt_lo = $008B     ; Camera altitude lo — subtracted from terrain height in transform_vertex
zp_cam_alt_hi = $008C     ; Camera altitude hi
zp_dir_quadrant = $0092     ; Direction quadrant selector — bits 7-6 choose transform variant in transform_vertex
zp_edge_x_arr = $0095     ; Edge sample X position array (indexed by Y) — terrain edge column positions
zp_edge_x_next = $0096     ; Next-level subdivided X position (indexed by Y) — output of midpoint bisection
zp_blend_row = $0097     ; Row counter for pixel blend loop in fill_column_fast phase 3
zp_frac_depth = $0098     ; Fractal recursion depth — terrain subdivision stack pointer
zp_frac_prev_depth = $0099     ; Previous fractal depth — compared against $98 to detect subdivision progress
zp_frac_delta_x = $009A     ; Fractal delta X — step direction for terrain subdivision (+1/-1/+16/-16)
zp_frac_delta_y = $009B     ; Fractal delta Y — perpendicular step for terrain subdivision
zp_frac_seed_pos = $009C     ; Current seed position in terrain height buffer
zp_norm_shift = $009F     ; Normalization shift count — saved by project_x, passed to/from div16
zp_disp_x_lo = $00A0     ; X displacement vector lo — camera heading projected to grid X step
zp_disp_x_hi = $00A1     ; X displacement vector hi
zp_disp_z_lo = $00A2     ; Z displacement vector lo — camera heading projected to grid Z step
zp_disp_z_hi = $00A3     ; Z displacement vector hi
zp_saved_x   = $00A8     ; Saved X register — used by terrain_render to preserve state across calls
zp_mul_result_lo = $00A9     ; 16-bit multiply result lo (output of mul16_signed)
zp_mul_result_hi = $00AA     ; 16-bit multiply result hi
zp_mul_cand_lo = $00AB     ; Multiply multiplicand lo (input to mul16_signed)
zp_mul_cand_hi = $00AC     ; Multiply multiplicand hi
zp_mul_plier = $00AD     ; Multiply multiplier (8-bit input, also used as shift register)
zp_mul_sign  = $00AE     ; Multiply sign save — bit 7 = negate result after unsigned multiply
zp_div_divisor_lo = $00AF     ; Division divisor lo (input to div16)
zp_div_divisor_hi = $00B0     ; Division divisor hi — BIT $B0 tests bit 6 for normalization
zp_div_remain_lo = $00B1     ; Division dividend/remainder lo
zp_div_remain_hi = $00B2     ; Division dividend/remainder hi
zp_div_quotient = $00B3     ; Division quotient (8-bit output of div16)
zp_terrain_idx = $00B5     ; Terrain index composite — combined grid X/row for heightmap lookup
zp_temp      = $00B6     ; Temp — Y save during pixel write, partial result during transform
zp_grid_row_accum = $00B7     ; Terrain grid row accumulator — accumulated row offset during vertex walk
zp_random_work = $00B8     ; Random perturbation workspace — used in terrain fractal generation
zp_screen_ptr_lo = $00BC     ; Screen pointer lo — heavy write, used in rendering copy loops
zp_screen_ptr_hi = $00BD     ; Screen pointer hi
zp_screen_ptr2_lo = $00BE     ; Secondary screen pointer lo — used in double-buffer/copy operations
zp_screen_ptr2_hi = $00BF     ; Secondary screen pointer hi
zp_color_work = $00C0     ; DLI/color workspace — R=20 W=18, used in color register programming
zp_memcpy_dst_lo = $00C2     ; Memcpy destination ptr lo — most-written ZP pair, used by memcpy_block
zp_memcpy_dst_hi = $00C3     ; Memcpy destination ptr hi
zp_memcpy_len_lo = $00C4     ; Memcpy length lo / general workspace
zp_memcpy_len_hi = $00C5     ; Memcpy length hi / general workspace
zp_render_scratch = $00C7     ; Rendering scratch variable
zp_dli_vec_lo = $00E1     ; DLI indirect jump vector lo — loaded from dli_jump_table, jumped through
zp_dli_vec_hi = $00E2     ; DLI indirect jump vector hi
zp_depth_arr = $00E3     ; Depth value array (indexed by Y) — terrain depth at each edge sample point
zp_depth_interp = $00E4     ; Interpolated depth output (indexed by Y) — result of midpoint averaging

; Game variables — Game state ($0603-$0A00)
game_ready_flag = $0603     ; Game ready/started flag — only written #$00, read by 3 procs
game_active_flag = $0604     ; Game active flag — only written #$01, read by 3 procs
game_phase_timer = $0605     ; Slow game phase timer — increments ~2 per 100 frames
frame_counter = $0609     ; Frame counter — incremented by VBI, used by wait_n_frames for sync
terrain_scroll_accum = $060C     ; Terrain scroll accumulator — smooth flight distance, ADC/SBC in terrain_render
terrain_scroll_rate = $060F     ; Terrain scroll rate — speed-dependent, SBC in terrain_render for distance calc
enabled_flag_0616 = $0616     ; Feature enabled flag — only written #$01
game_timer   = $061B     ; Game timer — R=9 W=4, frequently read counter
game_mode    = $061C     ; Game mode / level state — R=15 W=2, most-read state variable
slow_timer   = $0622     ; Slow timer — incremented by VBI title screen handler
game_event_flag = $0629     ; Game event flag — R=6 W=2, state_var, triggers game events
dirty_flag   = $0636     ; Changed/dirty flag — only written #$FF, read once (triggers redraw)
score_lo     = $0638     ; Score low byte — BCD, ADC with #$50 (500 points per pilot)
score_hi     = $0639     ; Score high byte — BCD, ADC with #$01/#$02
lives_or_fuel = $063B     ; Lives or fuel counter — value 02 at runtime
score_digit  = $063F     ; BCD score/lives digit — BCD increment at $656B
display_enabled = $0640     ; Display enabled flag — only written #$01, read by 3 procs
terrain_detail = $0641     ; Terrain distance/detail level — written by terrain_render based on camera distance
terrain_vis_flag = $0643     ; Terrain visibility flag — set #$80 when terrain close, $00 when far
slot_available = $0654     ; Entity slot available flag — only written #$00, read by 4 procs
ent_type     = $065F     ; Entity attribute table [0]: type/state — 14 entries, most accessed (24 ops, 15 procs)
ent_flags    = $066D     ; Entity attribute table [1]: flags — low nibble = entity subtype
ent_state    = $067B     ; Entity attribute table [2]: secondary state (14 ops, 9 procs)
ent_param_a  = $0689     ; Entity attribute table [3]: parameter A
ent_param_b  = $0697     ; Entity attribute table [4]: parameter B
ent_param_c  = $06A5     ; Entity attribute table [5]: parameter C
ent_param_d  = $06B3     ; Entity attribute table [6]: parameter D
ent_param_e  = $06C1     ; Entity attribute table [7]: parameter E
ent_param_f  = $06CF     ; Entity attribute table [8]: parameter F
ent_param_g  = $06DD     ; Entity attribute table [9]: parameter G
ent_param_h  = $06EB     ; Entity attribute table [10]: parameter H
ent_param_i  = $06F9     ; Entity attribute table [11]: parameter I
ent_active_flags = $0707     ; Entity active bitmap — 6 readers scan this, bits = entity type mask
cmd_queue_data = $071B     ; Command queue data — 32 slots, circular buffer, written by queue_push (25 writers)
cmd_queue_ptr = $073B     ; Command queue head/tail — most-accessed address in game (R=26, W=27)
row_addr_lo_blend = $0751     ; Screen row address table lo — for pixel blend in fill_column_fast phase 3
row_addr_hi_blend = $07A7     ; Screen row address table hi — paired with $0751 for indirect screen access
dat_0900     = $0900     ; 256-byte fractal terrain height ring buffer
pilot_map    = $0A00     ; 256-byte pilot location tracking buffer

; Game variables — Vertex arrays ($2270-$291C)
vtx_grid_idx = $2270     ; Vertex terrain grid index — 45 entries, maps vertex to heightmap position
vtx_cam_x_lo = $229D     ; Vertex camera-space X lo — 45 entries, accumulated from direction deltas
vtx_cam_x_hi = $22CB     ; Vertex camera-space X hi — 45 entries
vtx_cam_z_lo = $22F9     ; Vertex camera-space Z lo — 45 entries, used as divisor in perspective projection
vtx_cam_z_hi = $2327     ; Vertex camera-space Z hi — 45 entries
vtx_height_lo = $2355     ; Vertex scaled height lo — 45 entries, terrain height after altitude subtract + shift
vtx_height_hi = $2382     ; Vertex scaled height hi — 45 entries
vtx_raw_height = $23AF     ; Vertex raw terrain height — 45 entries, read from $0900 heightmap
vtx_screen_x_lo = $23DC     ; Vertex projected screen X lo — 45 entries, output of project_x X phase
vtx_screen_x_hi = $2409     ; Vertex projected screen X hi — 45 entries
vtx_screen_y_lo = $2436     ; Vertex projected screen Y lo — 45 entries, output of project_x Y phase
vtx_screen_y_hi = $2463     ; Vertex projected screen Y hi — 45 entries
vtx_vis_flags = $2490     ; Vertex visibility/projection flags — 45 entries: $80=behind, $40=right, $20=left, $10=projected, $00=visible
dat_24BE     = $24BE     ; Fractal midpoint displacement recursion stack
work_proj_x_lo = $2572     ; Working projected X lo — copied from vertex array for current edge pair
work_proj_x_hi = $2590     ; Working projected X hi
work_proj_y_lo = $25AE     ; Working projected Y lo
work_proj_y_hi = $25CC     ; Working projected Y hi
work_height  = $25EA     ; Working terrain height — for current edge pair
zbuf_columns = $2608     ; Per-column Z-buffer — 212 entries, depth of nearest terrain at each screen column
zbuf_sentinel_a = $2634     ; Z-buffer sentinel area A — initialized with $67 each frame for occlusion
zbuf_sentinel_b = $2648     ; Z-buffer sentinel area B — initialized with $6B, 4 sub-arrays of 33 bytes
horizon_profile = $2708     ; Horizon height profile — 32 entries, vertical offset per distance band
edge_iter_y_save = $2728     ; Edge iteration Y save — STY/LDY in terrain_render edge loop
saved_column_x = $27E9     ; Saved column X — STX at fill_terrain_column entry, LDX at exit
prev_detail_level = $2843     ; Previous terrain detail level — compared with $0641 to detect changes
render_state_flag = $2844     ; Rendering state flag — updated after terrain render
camera_view_param = $2882     ; Camera view parameter — R=9 W=2, affects terrain render initial setup
render_toggle = $2887     ; Rendering state toggle — values $00/$01, alternates per frame
cam_heading_lo = $289B     ; Camera heading angle lo — 16-bit, small changes = smooth turning
cam_heading_hi = $289C     ; Camera heading angle hi
cam_pitch_lo = $289D     ; Camera pitch angle lo — 16-bit, controls up/down view
cam_pitch_hi = $289E     ; Camera pitch angle hi
cam_altitude = $28A0     ; Camera altitude — height above terrain, value ~$2D during flight
flight_param = $28A4     ; Flight parameter — R=11 W=7, frequently read, affects terrain render
difficulty_level = $28A5     ; Difficulty/level parameter — R=14 W=1, near-constant (written once at level init)
terrain_near_dist = $28A9     ; Nearest terrain distance — computed per frame, controls detail level $0641
viewport_state = $28AC     ; Viewport state — R=11 W=11, rendering state counter
height_delta_tab = $28D0     ; Height delta table — 32 entries, terrain height differences for perspective
row_addr_lo_render = $28EC     ; Scanline address lo table — 48 entries, maps depth index to screen row address
current_vtx_idx = $28F6     ; Current vertex index — STX $28F6 in terrain_render, used for edge pair tracking
row_addr_hi_render = $291C     ; Scanline address hi table — 48 entries, paired with $28EC

; Game variables — Pixel rendering tables ($BC00-$BF00)
pix_color_mask = $BC00     ; Pixel color mask table — 256 entries, ORA mask for plotting pixel at column X
pix_byte_offset = $BD00     ; Pixel byte offset table — 212 entries, byte offset within scanline (rebuilt per frame)
pix_blend_cont = $BE00     ; Pixel blend continuation table — maps byte → next blend mask for ground fill
pix_blend_merge = $BF00     ; Pixel blend merge table — additional bits to OR for dithered fill transitions

; Game variables — page $C2 ($C2xx)
loc_C28A     = $C28A

; Game variables — page $D0 ($D0xx)
stub_D029    = $D029

; Game variables — page $E4 ($E4xx)
loc_E462     = $E462
