; Reconstructed from: behind_jaggi_lines.xex
; Generated by pyA8 reverse engineering toolkit
; Assemble with: mads main.asm -o:behind_jaggi_lines.xex

    opt h-      ; raw binary — XEX headers via ORG brackets

    icl 'equates.asm'

; === Segment 0: $3C00-$3C00 Placeholder byte at start addr ===
    org [a($FFFF),a($3C00),a($3C00)],$3C00
    icl 'seg_00_3C00.asm'

; === Segment 1: $3800-$3BFF Custom character set (128 chars) ===
    org [a($3800),a($3BFF)],$3800
    icl 'seg_01_3800.asm'

; === Segment 2: $3C00-$52E6 Game code + data: init, title screen, input, display lists ===
    org [a($3C00),a($52E6)],$3C00
    icl 'seg_02_3C00.asm'

; === Segment 3: $52E7-$852F Game code + data: game engine, AI, terrain, sound ===
    org [a($52E7),a($852F)],$52E7
    icl 'seg_03_52E7.asm'

; === Segment 4: $8530-$B7E6 Game code + data: rendering, tables, level data ===
    org [a($8530),a($B7E6)],$8530
    icl 'seg_04_8530.asm'

; === Segment 5: $0000-$0000 Padding byte ===
    org [a($0000),a($0000)],$0000
    icl 'seg_05_0000.asm'

; RUN address
    org [a($02E0),a($02E1)],$02E0
    .word game_start
