//	AltirraSDL - Font management for the Dear ImGui UI
//
//	Discovers TTF/OTF files under <exe>/fonts/ (or CWD/fonts/), exposes a
//	user-facing UI font and a separate monospace font, persists the choice
//	to the registry under Windows-compatible keys (Console: Font* for the
//	mono font; UI: Font* for the UI font), and rebuilds the ImGui font
//	atlas at end-of-frame whenever the user changes a setting.
//
//	The Configure System "Fonts" page (RenderFontsCategory) lives in this
//	file as well so all font logic stays in one place.

#include <stdafx.h>
#include <SDL3/SDL.h>
#include <imgui.h>
#include <imgui_impl_opengl3.h>
#include <imgui_impl_sdlrenderer3.h>
#include <vd2/system/vdtypes.h>
#include <vd2/system/VDString.h>
#include <vd2/system/registry.h>
#include <vd2/system/file.h>
#include <vd2/system/filesys.h>
#include <vd2/system/text.h>

#include <algorithm>
#include <cctype>
#include <cstring>
#include <vector>

#include "ui_fonts.h"
#include "logging.h"

// Embedded font blobs — generated by cmake/embed_font.cmake at build time.
// Always linked into the binary so the UI works on every platform without
// depending on a runtime fonts/ directory.
extern "C" {
	extern const unsigned char g_atFontRobotoMediumData[];
	extern const unsigned int  g_atFontRobotoMediumData_size;
	extern const unsigned char g_atFontFiraMonoRegularData[];
	extern const unsigned int  g_atFontFiraMonoRegularData_size;
}

// =========================================================================
// Discovered font records
// =========================================================================

struct ATFontFile {
	VDStringA family;     // e.g. "Roboto", "Fira Mono"
	VDStringA weight;     // e.g. "Regular", "Medium", "Bold", "Light", ...
	bool italic = false;
	bool monospaced = false;
	// Either a filesystem path, OR a "<builtin>" marker.  When mpBuiltinData
	// is non-null, the font is loaded from memory instead of disk and `path`
	// is just a human-readable label.
	VDStringA path;
	const unsigned char *mpBuiltinData = nullptr;
	unsigned int mBuiltinSize = 0;
};

static std::vector<ATFontFile> s_fontFiles;
static std::vector<VDStringA> s_uiFamilies;    // distinct, proportional first
static std::vector<VDStringA> s_monoFamilies;  // distinct, monospaced

// =========================================================================
// Active font configuration
// =========================================================================

namespace {
	constexpr const char *kDefaultUIFamily   = "Roboto";
	constexpr const char *kDefaultUIWeight   = "Medium";
	constexpr int         kDefaultUISize     = 11;   // points
	constexpr const char *kDefaultMonoFamily = "Fira Mono";
	constexpr const char *kDefaultMonoWeight = "Regular";
	constexpr int         kDefaultMonoSize   = 10;
}

static VDStringA s_uiFamily(kDefaultUIFamily);
static VDStringA s_uiWeight(kDefaultUIWeight);
static int       s_uiSize     = kDefaultUISize;

static VDStringA s_monoFamily(kDefaultMonoFamily);
static VDStringA s_monoWeight(kDefaultMonoWeight);
static int       s_monoSize   = kDefaultMonoSize;

static float s_contentScale = 1.0f;
static bool  s_dirty = false;
static bool  s_initialized = false;
static bool  s_usingGLBackend = false;

ImFont *g_pFontUI   = nullptr;
ImFont *g_pFontMono = nullptr;

// =========================================================================
// Helpers
// =========================================================================

static bool EndsWithCI(const VDStringA& s, const char *suffix) {
	const size_t n = strlen(suffix);
	if (s.size() < n) return false;
	for (size_t i = 0; i < n; ++i) {
		char a = (char)tolower((unsigned char)s[s.size() - n + i]);
		char b = (char)tolower((unsigned char)suffix[i]);
		if (a != b) return false;
	}
	return true;
}

// Parse a filename like "Roboto-MediumItalic.ttf" or "FiraMono-Regular.ttf"
// into family / weight / italic.  Variable-font filenames (those with
// "VariableFont" in them) are skipped — ImGui's stb_truetype loader does
// not honor variation axes, so the static instances are preferred.
static bool ParseFontFile(const VDStringA& filename, ATFontFile& out) {
	if (!EndsWithCI(filename, ".ttf") && !EndsWithCI(filename, ".otf"))
		return false;

	VDStringA stem(filename);
	stem.resize(stem.size() - 4);

	if (strstr(stem.c_str(), "VariableFont") || strstr(stem.c_str(), "variableFont"))
		return false;

	// Family is everything before the first '-'; suffix after is the style.
	const char *dash = strchr(stem.c_str(), '-');
	VDStringA family;
	VDStringA suffix;
	if (dash) {
		family.assign(stem.c_str(), dash - stem.c_str());
		suffix = dash + 1;
	} else {
		family = stem;
		suffix = "Regular";
	}

	// Pretty-print common family names: "FiraMono" -> "Fira Mono",
	// "Roboto_Condensed" -> "Roboto Condensed".
	{
		VDStringA pretty;
		for (size_t i = 0; i < family.size(); ++i) {
			char c = family[i];
			if (c == '_') {
				pretty += ' ';
				continue;
			}
			if (i > 0 && isupper((unsigned char)c) &&
				islower((unsigned char)family[i-1]) &&
				pretty.size() && pretty[pretty.size()-1] != ' ')
			{
				pretty += ' ';
			}
			pretty += c;
		}
		family = pretty;
	}

	bool italic = false;
	if (const char *it = strstr(suffix.c_str(), "Italic")) {
		italic = true;
		// strip "Italic" from suffix
		size_t pos = it - suffix.c_str();
		suffix.erase(pos, 6);
		if (suffix.empty()) suffix = "Regular";
	}

	out.family = family;
	out.weight = suffix;
	out.italic = italic;
	out.monospaced = (strstr(family.c_str(), "Mono") != nullptr) ||
	                 (strstr(family.c_str(), "mono") != nullptr);
	return true;
}

static void ScanFontDir(const VDStringA& dir) {
	// Recursive scan: top-level *.ttf, then any one-level subdirs (e.g.
	// Roboto/static/, Fira_Mono/).  We avoid the heavyweight VDDirectoryIterator
	// dependency and use SDL's enumerator since SDL3 is already linked.
	struct Ctx {
		VDStringA base;
		void Scan(const VDStringA& d) {
			SDL_EnumerateDirectoryCallback cb = [](void *ud, const char *dirname, const char *fname) -> SDL_EnumerationResult {
				auto *self = (Ctx *)ud;
				VDStringA full = VDStringA(dirname);
				if (!full.empty() && full[full.size()-1] != '/' && full[full.size()-1] != '\\')
					full += '/';
				full += fname;

				SDL_PathInfo info {};
				if (!SDL_GetPathInfo(full.c_str(), &info))
					return SDL_ENUM_CONTINUE;

				if (info.type == SDL_PATHTYPE_DIRECTORY) {
					self->Scan(full);
				} else if (info.type == SDL_PATHTYPE_FILE) {
					ATFontFile rec;
					if (ParseFontFile(VDStringA(fname), rec)) {
						rec.path = full;
						s_fontFiles.push_back(std::move(rec));
					}
				}
				return SDL_ENUM_CONTINUE;
			};
			SDL_EnumerateDirectory(d.c_str(), cb, this);
		}
	} ctx;
	ctx.base = dir;
	ctx.Scan(dir);
}

static void RebuildFamilyLists() {
	s_uiFamilies.clear();
	s_monoFamilies.clear();
	for (const auto& f : s_fontFiles) {
		auto& target = f.monospaced ? s_monoFamilies : s_uiFamilies;
		if (std::find(target.begin(), target.end(), f.family) == target.end())
			target.push_back(f.family);
	}
	std::sort(s_uiFamilies.begin(), s_uiFamilies.end());
	std::sort(s_monoFamilies.begin(), s_monoFamilies.end());
	// If there are no monospaced families discovered, fall back to UI list
	// so the user always has *something* to pick.
	if (s_monoFamilies.empty())
		s_monoFamilies = s_uiFamilies;
}

// Pick the best file for the requested (family, weight) pair.  Falls back
// to Regular weight, then any file in the family, then any file at all.
static const ATFontFile *PickFontFile(const char *family, const char *weight) {
	const ATFontFile *exact = nullptr, *familyRegular = nullptr, *anyInFamily = nullptr;
	for (const auto& f : s_fontFiles) {
		if (f.italic) continue;
		if (f.family != family) continue;
		if (!anyInFamily) anyInFamily = &f;
		if (f.weight == "Regular") familyRegular = &f;
		if (f.weight == weight) { exact = &f; break; }
	}
	if (exact) return exact;
	if (familyRegular) return familyRegular;
	if (anyInFamily) return anyInFamily;
	return s_fontFiles.empty() ? nullptr : &s_fontFiles[0];
}

// =========================================================================
// Atlas (re)build
// =========================================================================

// Build a static glyph range covering Latin-1, Latin Extended, Greek, and
// Cyrillic via ImFontGlyphRangesBuilder.  Persistent storage is required
// because ImGui keeps the pointer until the atlas is built.
static const ImWchar *GetUIFontGlyphRanges() {
	static ImVector<ImWchar> ranges;
	if (ranges.empty()) {
		ImFontGlyphRangesBuilder builder;
		ImFontAtlas *atlas = ImGui::GetIO().Fonts;
		builder.AddRanges(atlas->GetGlyphRangesDefault());   // Basic Latin + Latin-1
		builder.AddRanges(atlas->GetGlyphRangesCyrillic());  // ~400 Cyrillic glyphs
		builder.AddRanges(atlas->GetGlyphRangesGreek());     // Greek + Coptic
		// Latin Extended-A and Extended-B (Western/Central European accents
		// not covered by Latin-1: ą ć ę ł ń ś ź ż ř š č etc.)
		static const ImWchar kLatinExt[] = { 0x0100, 0x024F, 0 };
		builder.AddRanges(kLatinExt);
		// General Punctuation (en-dash, em-dash, smart quotes, ellipsis,
		// bullet, trade/service marks) — common in game pack file names.
		static const ImWchar kPunctuation[] = { 0x2000, 0x206F, 0 };
		builder.AddRanges(kPunctuation);
		// Letterlike Symbols (trademark ™ etc.)
		static const ImWchar kLetterlike[] = { 0x2100, 0x214F, 0 };
		builder.AddRanges(kLetterlike);
		builder.BuildRanges(&ranges);
	}
	return ranges.Data;
}

// Mono font: keep the atlas small — debugger panes display ASCII + a few
// box-drawing chars.  Default range (Basic Latin + Latin-1) is enough.
static const ImWchar *GetMonoFontGlyphRanges() {
	return ImGui::GetIO().Fonts->GetGlyphRangesDefault();
}

static void LoadFontFromFile(const ATFontFile *file, float pixelSize,
	const ImWchar *glyphRanges, ImFont*& out)
{
	out = nullptr;
	if (!file) return;

	const void *srcData = nullptr;
	size_t srcSize = 0;
	void *sdlData = nullptr;

	if (file->mpBuiltinData) {
		// Embedded blob — point at the linker-provided data directly.
		srcData = file->mpBuiltinData;
		srcSize = file->mBuiltinSize;
	} else {
		sdlData = SDL_LoadFile(file->path.c_str(), &srcSize);
		if (!sdlData || srcSize == 0) {
			LOG_INFO("UI", "Font load failed: %s", file->path.c_str());
			if (sdlData) SDL_free(sdlData);
			return;
		}
		srcData = sdlData;
	}

	// Always copy through ImGui's allocator so FontDataOwnedByAtlas can
	// safely IM_FREE() it later.  Embedded data must NOT be freed; copying
	// keeps that ownership invariant simple.
	void *imgData = IM_ALLOC(srcSize);
	memcpy(imgData, srcData, srcSize);
	if (sdlData) SDL_free(sdlData);

	ImFontConfig cfg;
	cfg.FontDataOwnedByAtlas = true;

	ImGuiIO& io = ImGui::GetIO();
	out = io.Fonts->AddFontFromMemoryTTF(imgData, (int)srcSize, pixelSize, &cfg, glyphRanges);
}

static void RebuildAtlas() {
	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->Clear();

	const float uiPx   = (float)s_uiSize   * s_contentScale * 96.0f / 72.0f;
	const float monoPx = (float)s_monoSize * s_contentScale * 96.0f / 72.0f;

	LOG_INFO("UI", "Font rebuild: uiSize=%d monoSize=%d contentScale=%.2f uiPx=%.1f monoPx=%.1f FontGlobalScale=%.2f",
		s_uiSize, s_monoSize, s_contentScale, uiPx, monoPx, ImGui::GetIO().FontGlobalScale);

	const ATFontFile *uiFile   = PickFontFile(s_uiFamily.c_str(),   s_uiWeight.c_str());
	const ATFontFile *monoFile = PickFontFile(s_monoFamily.c_str(), s_monoWeight.c_str());

	LoadFontFromFile(uiFile,   uiPx,   GetUIFontGlyphRanges(),   g_pFontUI);
	LoadFontFromFile(monoFile, monoPx, GetMonoFontGlyphRanges(), g_pFontMono);

	if (!g_pFontUI) {
		// Last-resort fallback: ImGui's built-in ProggyClean bitmap font.
		// Reached only if every TTF (including the embedded one) failed
		// to load, e.g. due to memory pressure or a corrupted blob.
		LOG_INFO("UI", "All TTF fonts failed to load — using ProggyClean fallback");
		g_pFontUI = io.Fonts->AddFontDefault();
	}
	if (!g_pFontMono) {
		g_pFontMono = g_pFontUI;
	}

	io.FontDefault = g_pFontUI;
	io.Fonts->Build();
}

// =========================================================================
// Registry I/O
// =========================================================================

static const char *kRegPath = "Settings";

static void LoadFromRegistry() {
	VDRegistryAppKey key(kRegPath, false);

	VDStringW tmp;
	if (key.getString("UI: Font family", tmp))
		s_uiFamily = VDTextWToA(tmp);
	if (key.getString("UI: Font weight", tmp))
		s_uiWeight = VDTextWToA(tmp);
	int v = key.getInt("UI: Font point size tenths", 0);
	if (v > 0) s_uiSize = v / 10;

	if (key.getString("Console: Font family", tmp))
		s_monoFamily = VDTextWToA(tmp);
	if (key.getString("Console: Font weight", tmp))
		s_monoWeight = VDTextWToA(tmp);
	v = key.getInt("Console: Font point size tenths", 0);
	if (v > 0) s_monoSize = v / 10;
}

static void SaveToRegistry() {
	VDRegistryAppKey key(kRegPath, true);
	key.setString("UI: Font family", VDTextAToW(s_uiFamily.c_str()).c_str());
	key.setString("UI: Font weight", VDTextAToW(s_uiWeight.c_str()).c_str());
	key.setInt("UI: Font point size tenths", s_uiSize * 10);

	key.setString("Console: Font family", VDTextAToW(s_monoFamily.c_str()).c_str());
	key.setString("Console: Font weight", VDTextAToW(s_monoWeight.c_str()).c_str());
	key.setInt("Console: Font point size tenths", s_monoSize * 10);
}

// =========================================================================
// Public API
// =========================================================================

void ATUIFontsInit(float contentScale, bool usingGLBackend) {
	s_contentScale = contentScale > 0 ? contentScale : 1.0f;
	s_usingGLBackend = usingGLBackend;
	s_initialized = true;

	// Discover fonts: embedded blobs first (always present, never fails),
	// then <exe_dir>/fonts/ for user-supplied additions, then CWD fallback.
	s_fontFiles.clear();

	// --- Embedded fonts (always available) ---
	{
		ATFontFile rec;
		rec.family       = "Roboto";
		rec.weight       = "Medium";
		rec.italic       = false;
		rec.monospaced   = false;
		rec.path         = "<builtin:roboto-medium>";
		rec.mpBuiltinData = g_atFontRobotoMediumData;
		rec.mBuiltinSize  = g_atFontRobotoMediumData_size;
		s_fontFiles.push_back(rec);

		rec.family       = "Fira Mono";
		rec.weight       = "Regular";
		rec.monospaced   = true;
		rec.path         = "<builtin:firamono-regular>";
		rec.mpBuiltinData = g_atFontFiraMonoRegularData;
		rec.mBuiltinSize  = g_atFontFiraMonoRegularData_size;
		s_fontFiles.push_back(rec);
	}

	// --- User-supplied additions: scan <exe>/fonts/, then CWD/fonts/. ---
	// Embedded fonts already cover the default experience; this is purely
	// for users who want extra families.  Both scans are best-effort.
	const size_t builtinCount = s_fontFiles.size();
	const char *base = SDL_GetBasePath();
	if (base && *base) {
		VDStringA dir(base);
		dir += "fonts";
		ScanFontDir(dir);
	}
	if (s_fontFiles.size() == builtinCount) {
		ScanFontDir(VDStringA("fonts"));
	}

	RebuildFamilyLists();
	LoadFromRegistry();

	LOG_INFO("UI", "Fonts: discovered %zu files, %zu UI families, %zu mono families",
		s_fontFiles.size(), s_uiFamilies.size(), s_monoFamilies.size());

	RebuildAtlas();
	s_dirty = false;
}

void ATUIFontsRebuildIfDirty() {
	if (!s_dirty || !s_initialized) return;
	s_dirty = false;

	// Tear down the current backend texture so the next NewFrame uploads
	// a fresh one built from the new atlas.
	if (s_usingGLBackend) {
		ImGui_ImplOpenGL3_DestroyFontsTexture();
	} else {
		ImGui_ImplSDLRenderer3_DestroyFontsTexture();
	}

	RebuildAtlas();
	SaveToRegistry();
}

ImFont *ATUIGetFontUI() {
	if (g_pFontUI)
		return g_pFontUI;
	return ImGui::GetIO().FontDefault;
}

ImFont *ATUIGetFontMono() {
	if (g_pFontMono)
		return g_pFontMono;
	if (g_pFontUI)
		return g_pFontUI;
	return ImGui::GetIO().FontDefault;
}

// =========================================================================
// Configure System -> Emulator -> Fonts page
// =========================================================================

class ATSimulator;

static int FindIndex(const std::vector<VDStringA>& v, const VDStringA& s) {
	for (size_t i = 0; i < v.size(); ++i)
		if (v[i] == s) return (int)i;
	return -1;
}

// Lists weight names available for a given family (excluding italic variants).
static std::vector<VDStringA> CollectWeights(const char *family) {
	std::vector<VDStringA> out;
	for (const auto& f : s_fontFiles) {
		if (f.italic) continue;
		if (f.family != family) continue;
		if (std::find(out.begin(), out.end(), f.weight) == out.end())
			out.push_back(f.weight);
	}
	std::sort(out.begin(), out.end());
	return out;
}

static void RenderFamilyCombo(const char *label,
	const std::vector<VDStringA>& families,
	VDStringA& currentFamily,
	VDStringA& currentWeight)
{
	int idx = FindIndex(families, currentFamily);
	std::vector<const char *> items;
	items.reserve(families.size());
	for (const auto& f : families) items.push_back(f.c_str());

	if (families.empty()) {
		ImGui::TextDisabled("(no fonts found in fonts/ directory)");
		return;
	}

	if (idx < 0) idx = 0;
	if (ImGui::Combo(label, &idx, items.data(), (int)items.size())) {
		currentFamily = families[idx];
		// Reset weight to a valid choice for the new family
		auto weights = CollectWeights(currentFamily.c_str());
		if (std::find(weights.begin(), weights.end(), currentWeight) == weights.end())
			currentWeight = weights.empty() ? VDStringA("Regular") : weights.front();
		s_dirty = true;
	}
}

static void RenderWeightCombo(const char *label, const char *family, VDStringA& currentWeight) {
	auto weights = CollectWeights(family);
	if (weights.empty()) return;

	std::vector<const char *> items;
	items.reserve(weights.size());
	for (const auto& w : weights) items.push_back(w.c_str());

	int idx = -1;
	for (size_t i = 0; i < weights.size(); ++i)
		if (weights[i] == currentWeight) { idx = (int)i; break; }
	if (idx < 0) {
		idx = 0;
		currentWeight = weights[0];
	}
	if (ImGui::Combo(label, &idx, items.data(), (int)items.size())) {
		currentWeight = weights[idx];
		s_dirty = true;
	}
}

void RenderFontsCategory(ATSimulator &) {
	ImGui::TextWrapped(
		"Choose the fonts used by the Altirra UI.  TTF/OTF files placed in the "
		"\"fonts\" directory next to the executable are picked up automatically. "
		"Changes apply immediately and are saved on exit.");
	ImGui::Spacing();

	// ----- UI Font -----
	ImGui::SeparatorText("UI Font");
	ImGui::TextDisabled("Used for menus, dialogs, and text in the emulator UI.");
	RenderFamilyCombo("Family##ui", s_uiFamilies, s_uiFamily, s_uiWeight);
	RenderWeightCombo("Weight##ui", s_uiFamily.c_str(), s_uiWeight);
	if (ImGui::SliderInt("Size (pt)##ui", &s_uiSize, 8, 32, "%d pt")) {
		s_dirty = true;
	}
	ImGui::SetItemTooltip("Drag or click; the change applies on the next frame.");

	// Live preview using the currently active font (rebuilt at end of frame).
	if (g_pFontUI) {
		ImGui::PushFont(g_pFontUI);
		ImGui::TextUnformatted("Preview: The quick brown fox jumps over the lazy dog 0123456789");
		ImGui::PopFont();
	}
	ImGui::Spacing();

	// ----- Monospace Font -----
	ImGui::SeparatorText("Monospace Font");
	ImGui::TextDisabled(
		"Used for the debugger panes (disassembly, memory, history, console).");
	RenderFamilyCombo("Family##mono", s_monoFamilies, s_monoFamily, s_monoWeight);
	RenderWeightCombo("Weight##mono", s_monoFamily.c_str(), s_monoWeight);
	if (ImGui::SliderInt("Size (pt)##mono", &s_monoSize, 8, 32, "%d pt")) {
		s_dirty = true;
	}

	if (g_pFontMono) {
		ImGui::PushFont(g_pFontMono);
		ImGui::TextUnformatted("Preview: lda $D01A   ; 0xDEADBEEF  iiii  WWWW  ....");
		ImGui::PopFont();
	}
	ImGui::Spacing();

	// ----- Reset -----
	ImGui::Separator();
	if (ImGui::Button("Reset to Defaults")) {
		s_uiFamily   = kDefaultUIFamily;
		s_uiWeight   = kDefaultUIWeight;
		s_uiSize     = kDefaultUISize;
		s_monoFamily = kDefaultMonoFamily;
		s_monoWeight = kDefaultMonoWeight;
		s_monoSize   = kDefaultMonoSize;
		s_dirty = true;
	}
	ImGui::SameLine();
	ImGui::TextDisabled("Roboto Medium 16 pt / Fira Mono Regular 14 pt");
}
