; Reconstructed from: koronis_rift_128k.xex
; Generated by pyA8 reverse engineering toolkit
; Assemble with: mads main.asm -o:koronis_rift_128k.xex

    opt h-      ; raw binary — XEX headers via ORG brackets

    icl 'equates.asm'

; === Segment 0: $2020-$203A Game setup code - screen address pointers ===
    org [a($FFFF),a($2020),a($203A)],$2020
    icl 'seg_00_2020.asm'

; === Segment 1: $0244-$0244 COLDST = $01 - prevent cold start ===
    org [a($0244),a($0244)],$0244
    icl 'seg_01_0244.asm'

; === Segment 2: $D301-$D301 PORTB = $FF - main memory, ROM enabled ===
    org [a($D301),a($D301)],$D301
    icl 'seg_02_D301.asm'

; === Segment 3: $022F-$022F SDMCTL = $00 - disable display ===
    org [a($022F),a($022F)],$022F
    icl 'seg_03_022F.asm'

; === Segment 4: $D400-$D400 DMACTL = $00 - disable ANTIC DMA ===
    org [a($D400),a($D400)],$D400
    icl 'seg_04_D400.asm'

; === Segment 5: $0041-$0041 Unknown flag at $41 ===
    org [a($0041),a($0041)],$0041
    icl 'seg_05_0041.asm'

; === Segment 6: $33AA-$37FF Title screen init: splash, music, keypress wait ===
    org [a($33AA),a($37FF)],$33AA
    icl 'seg_06_33AA.asm'

; INI: title_screen_init
    org [a($02E2),a($02E3)],$02E2
    .word title_screen_init

; === Segment 7: $B504-$B658 Decompressor routine at B504-B658 ===
    org [a($B504),a($B658)],$B504
    icl 'seg_07_B504.asm'

; === Segment 8: $B500-$B503 Decomp params for seg 9 data ($0F00-$1AF5) ===
    org [a($B500),a($B503)],$B500
    icl 'seg_08_B500.asm'

; === Segment 9: $0F00-$1AF5 Display list + screen data (compressed) ===
    org [a($0F00),a($1AF5)],$0F00
    icl 'seg_09_0F00.asm'

; INI: decompress
    org [a($02E2),a($02E3)],$02E2
    .word decompress

; INI: $2F90
    org [a($02E2),a($02E3)],$02E2
    .word $2F90

; === Segment 10: $0100-$0171 Stack area initialization ===
    org [a($0100),a($0171)],$0100
    icl 'seg_10_0100.asm'

; === Segment 11: $4000-$7723 Bank data loaded to $4000-$7723 (main bank, compressed) ===
    org [a($4000),a($7723)],$4000
    icl 'seg_11_4000.asm'

; === Segment 12: $D301-$D301 PORTB = $E7 - switch to bank 1 (130XE) ===
    org [a($D301),a($D301)],$D301
    icl 'seg_12_D301.asm'

; === Segment 13: $4000-$7AB4 Bank 1 data ($4000-$7AB4) ===
    org [a($4000),a($7AB4)],$4000
    icl 'seg_13_4000.asm'

; === Segment 14: $D301-$D301 PORTB = $EB - switch to bank 2 (130XE) ===
    org [a($D301),a($D301)],$D301
    icl 'seg_14_D301.asm'

; === Segment 15: $4000-$7B89 Bank 2 data ($4000-$7B89) ===
    org [a($4000),a($7B89)],$4000
    icl 'seg_15_4000.asm'

; === Segment 16: $D301-$D301 PORTB = $EF - switch to bank 3 (130XE) ===
    org [a($D301),a($D301)],$D301
    icl 'seg_16_D301.asm'

; === Segment 17: $4000-$7329 Bank 3 data ($4000-$7329) ===
    org [a($4000),a($7329)],$4000
    icl 'seg_17_4000.asm'

; === Segment 18: $7800-$79A2 Init code at $7800-$79A2 ===
    org [a($7800),a($79A2)],$7800
    icl 'seg_18_7800.asm'

; === Segment 19: $B500-$B503 Decomp params for seg 20 data ===
    org [a($B500),a($B503)],$B500
    icl 'seg_19_B500.asm'

; === Segment 20: $7B00-$7BBD Additional data at $7B00-$7BBD (compressed) ===
    org [a($7B00),a($7BBD)],$7B00
    icl 'seg_20_7B00.asm'

; INI: decompress
    org [a($02E2),a($02E3)],$02E2
    .word decompress

; === Segment 21: $D301-$D301 PORTB = $FF - back to main memory ===
    org [a($D301),a($D301)],$D301
    icl 'seg_21_D301.asm'

; === Segment 22: $B500-$B503 Decomp params for seg 23 data ===
    org [a($B500),a($B503)],$B500
    icl 'seg_22_B500.asm'

; === Segment 23: $5000-$671B Data at $5000-$671B ===
    org [a($5000),a($671B)],$5000
    icl 'seg_23_5000.asm'

; INI: decompress
    org [a($02E2),a($02E3)],$02E2
    .word decompress

; INI: $7800
    org [a($02E2),a($02E3)],$02E2
    .word $7800

; === Segment 24: $B500-$B503 Decomp params for final segment ===
    org [a($B500),a($B503)],$B500
    icl 'seg_24_B500.asm'

; === Segment 25: $3680-$87CB Main game code $3680-$87CB (compressed, final) ===
    org [a($3680),a($87CB)],$3680
    icl 'seg_25_3680.asm'

; INI: decompress
    org [a($02E2),a($02E3)],$02E2
    .word decompress

; INI: $B100
    org [a($02E2),a($02E3)],$02E2
    .word $B100
