"""MADS source exporter.

Take a :class:`~altirra_bridge.project.Project` plus a connected
:class:`~altirra_bridge.client.AltirraBridge` and produce an
assemblable MADS source file. The disassembly itself comes straight
from the bridge's ``DISASM`` command (Altirra's own
``ATDisassembleInsn``); we layer labels and comments from the
project on top.

The output is intentionally minimal — labels at their addresses,
comments after instructions, ``ORG`` directives at segment
boundaries. No macros, no equates, no fancy formatting. The goal is
"recompile this with MADS and produce a byte-identical binary",
not "produce something a human enjoys reading". For the latter,
hand-edit the output.

Workflow
--------

1. Boot or load the binary into the bridge so its address space is
   populated.
2. Use :func:`emit_segment` to write a single contiguous range, or
   :func:`emit_xex` to walk every segment of an :class:`XexImage`.
3. Round-trip verify by assembling with MADS and comparing the
   resulting XEX/binary against the original (the project's
   :attr:`~Project.source_path`).
"""

from __future__ import annotations

from typing import IO, Iterable, List, Optional, TextIO

from .client import AltirraBridge
from .loader import XexImage, XexSegment
from .project import Project


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _label_for(proj: Project, addr: int) -> Optional[str]:
    return proj.labels.get(addr) if proj else None


def _comment_for(proj: Project, addr: int) -> Optional[str]:
    return proj.comments.get(addr) if proj else None


def _strip_inline_address(text: str) -> str:
    """Altirra's disassembly text starts with the source label or
    address column followed by the mnemonic+operand. We want only
    the right-hand mnemonic side because we're emitting our own
    label column from the project.

    The format is something like ``"LBL  jmp $EED8    [$EED8] = $78"``
    or ``"     jmp $EED8"``. Strip an optional leading word followed
    by whitespace, then strip a trailing ``"[...] = ..."`` reference
    annotation.
    """
    s = text.strip()
    # Drop trailing reference annotation, e.g. " [$EED8] = $78".
    if "    [" in s:
        s = s.split("    [", 1)[0].rstrip()
    elif "  [" in s:
        s = s.split("  [", 1)[0].rstrip()
    # Drop leading symbolic label column. Altirra emits an
    # uppercase label of >=2 chars followed by 2+ spaces; the
    # mnemonic is lowercase. Detect by "mnemonic starts mid-line".
    parts = s.split(None, 1)
    if len(parts) == 2 and parts[0].isupper() and len(parts[0]) >= 2:
        # Heuristic: if the second part starts with a 3-letter
        # lowercase op (jmp, lda, sta, ...), the first token is a
        # label we already render ourselves. Drop it.
        rest = parts[1].lstrip()
        if rest[:3].islower() and rest[:3].isalpha():
            return rest
    return s


# ---------------------------------------------------------------------------
# Public emitters
# ---------------------------------------------------------------------------

def emit_header(out: TextIO, proj: Project) -> None:
    """Write a banner comment block identifying the project."""
    out.write("; ----------------------------------------------------------\n")
    out.write(f"; MADS source for project: {proj.name}\n")
    if proj.source_path:
        out.write(f"; original binary:        {proj.source_path}\n")
    out.write(";\n")
    out.write("; Generated by altirra_bridge.asm_writer.\n")
    out.write("; Disassembly is from Altirra ATDisassembleInsn via the\n")
    out.write("; AltirraBridge DISASM command. Labels and comments are\n")
    out.write("; from the project file.\n")
    out.write("; ----------------------------------------------------------\n")
    out.write("\n")


def emit_labels(out: TextIO, proj: Project) -> None:
    """Emit ``label = $addr`` equates for every label in the project
    *outside* the segments we're disassembling. The disassembly
    pass already attaches in-segment labels at their addresses; this
    pass exposes the labels for memory locations the disassembly
    references but doesn't define (registers, RAM variables, OS
    vectors, etc.).
    """
    if not proj.labels:
        return
    out.write("; --- equates ---\n")
    for addr in sorted(proj.labels):
        out.write(f"{proj.labels[addr]:<16} = ${addr:04x}\n")
    out.write("\n")


def emit_segment(
    out:    TextIO,
    bridge: AltirraBridge,
    start:  int,
    end:    int,
    proj:   Optional[Project] = None,
) -> None:
    """Disassemble ``[start, end]`` from the running emulator and
    write MADS source to ``out``. Inserts an ``ORG`` directive at
    ``start``, then walks one instruction at a time using bridge
    ``DISASM`` calls.

    The bridge call is per-instruction (not bulk) so the disassembler
    sees the *current* CPU state for each step — important for
    65C816 mode where the M/X flags affect operand width. For 6502
    targets you could batch by passing a larger ``count`` and
    iterating client-side, but the per-instruction loop is fast
    enough (<5ms for a 16K segment over loopback TCP).
    """
    proj = proj or Project.new("export")

    out.write(f"\n        org ${start:04x}\n")
    pc = start
    while pc <= end:
        result = bridge.disasm(pc, count=1)
        if not result:
            out.write(f"; DISASM returned nothing at ${pc:04x}\n")
            break
        ins = result[0]
        addr = int(ins["addr"].lstrip("$"), 16)

        label = _label_for(proj, addr)
        if label:
            out.write(f"{label}:\n")

        # Emit instruction with optional inline comment.
        text = _strip_inline_address(ins["text"])
        comment = _comment_for(proj, addr)
        if comment:
            out.write(f"        {text:<32}; {comment}\n")
        else:
            out.write(f"        {text}\n")

        next_pc = int(ins["next"].lstrip("$"), 16)
        if next_pc <= pc:  # safety against infinite loops on bad data
            break
        pc = next_pc


def emit_xex(
    out:    TextIO,
    bridge: AltirraBridge,
    image:  XexImage,
    proj:   Optional[Project] = None,
) -> None:
    """Emit every segment of an XEX image as MADS source.

    The init/run vectors are written as MADS ``ini`` / ``run``
    pseudo-ops at the bottom so the produced source assembles
    back to a fresh XEX with the original entry behaviour.
    """
    proj = proj or Project.new("export")
    emit_header(out, proj)
    emit_labels(out, proj)

    for i, seg in enumerate(image.segments):
        out.write(f"\n; --- segment {i}: ${seg.start:04x}-${seg.end:04x} "
                  f"({seg.length} bytes) ---\n")
        emit_segment(out, bridge, seg.start, seg.end, proj)

    out.write("\n; --- entry / init ---\n")
    if image.runad is not None:
        out.write(f"        run ${image.runad:04x}\n")
    for ia in image.initads:
        out.write(f"        ini ${ia:04x}\n")
    out.write("\n; end of file\n")


def export_xex_to_file(
    bridge: AltirraBridge,
    image:  XexImage,
    proj:   Project,
    path:   str,
) -> None:
    """Convenience: write a full XEX disassembly to ``path``."""
    with open(path, "w", encoding="utf-8") as f:
        emit_xex(f, bridge, image, proj)
