//	AltirraSDL - Online Play UI state (impl)

#include <stdafx.h>

#include "ui_netplay_state.h"

#include <vd2/system/registry.h>
#include <vd2/system/VDString.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>

namespace ATNetplayUI {

namespace {

State g_state;
bool  g_initialized = false;

// Consonant/vowel tables for a pronounceable 8-char handle.  Avoids
// ambiguous letters (I/l/1, O/0) and vulgar syllables (by never
// placing two consonants in a row).
const char kConsonants[] = "bcdfghjkmnpqrstvwxyz";
const char kVowels[]     = "aeiou";

// Small xorshift for RNG so we don't pollute the global rand() sequence.
uint32_t NextRand() {
	static uint32_t s = 0;
	if (s == 0) {
		s = (uint32_t)(std::time(nullptr) ^ 0x9E3779B1u);
		if (s == 0) s = 1;
	}
	s ^= s << 13; s ^= s >> 17; s ^= s << 5;
	return s;
}

std::string AnonName() {
	char buf[9];
	for (int i = 0; i < 8; ++i) {
		const char* table = (i & 1) ? kVowels : kConsonants;
		size_t n = (i & 1) ? (sizeof kVowels - 1) : (sizeof kConsonants - 1);
		buf[i] = table[NextRand() % n];
	}
	buf[8] = 0;
	// Capitalise the first letter so it looks like a name.
	if (buf[0] >= 'a' && buf[0] <= 'z') buf[0] = (char)(buf[0] - 32);
	return std::string(buf, 8);
}

// Cache for ResolvedNickname().  Cleared on Shutdown().
std::string g_resolvedCache;

} // anonymous

State& GetState() { return g_state; }

std::string GenerateAnonymousNickname() { return AnonName(); }

const std::string& ResolvedNickname() {
	if (!g_state.prefs.nickname.empty()) return g_state.prefs.nickname;
	if (g_resolvedCache.empty()) g_resolvedCache = AnonName();
	return g_resolvedCache;
}

// -----------------------------------------------------------------------
// Registry I/O
// -----------------------------------------------------------------------

// Load all hosted hostedGames from the registry.  Keys:
//   GameCount       : int    — number of entries to read
//   Offer<N>_id      : str    — stable local id
//   Offer<N>_path    : str    — UTF-8 image path
//   Offer<N>_name    : str    — basename / library display name
//   Offer<N>_art     : str    — optional cartArtHash (hex)
//   Offer<N>_private : bool
//   Offer<N>_code    : str    — entry code (cleartext)
//   Offer<N>_enabled : bool
// Runtime fields (state/port/token) are never persisted; they rebuild
// on each Initialize from the reconcile loop.
static void LoadOffers(VDRegistryAppKey& key) {
	int count = key.getInt("GameCount", 0);
	if (count < 0) count = 0;
	if ((size_t)count > State::kMaxHostedGames)
		count = (int)State::kMaxHostedGames;

	g_state.hostedGames.clear();
	g_state.hostedGames.reserve(count);

	for (int i = 0; i < count; ++i) {
		char knId[16], knPath[16], knName[16], knArt[16],
		     knPriv[16], knCode[16], knEn[16];
		std::snprintf(knId,   sizeof knId,   "Game%d_id",      i);
		std::snprintf(knPath, sizeof knPath, "Game%d_path",    i);
		std::snprintf(knName, sizeof knName, "Game%d_name",    i);
		std::snprintf(knArt,  sizeof knArt,  "Game%d_art",     i);
		std::snprintf(knPriv, sizeof knPriv, "Game%d_private", i);
		std::snprintf(knCode, sizeof knCode, "Game%d_code",    i);
		std::snprintf(knEn,   sizeof knEn,   "Game%d_enabled", i);

		char knPreset[16];
		std::snprintf(knPreset, sizeof knPreset, "Game%d_preset", i);

		HostedGame o;
		VDStringA buf;
		if (key.getString(knId, buf))   o.id.assign(buf.c_str(), buf.size());
		if (key.getString(knPath, buf)) o.gamePath.assign(buf.c_str(), buf.size());
		if (key.getString(knName, buf)) o.gameName.assign(buf.c_str(), buf.size());
		if (key.getString(knArt, buf))  o.cartArtHash.assign(buf.c_str(), buf.size());
		o.isPrivate = key.getBool(knPriv, false);
		if (key.getString(knCode, buf)) o.entryCode.assign(buf.c_str(), buf.size());
		// Always start disabled on restart — users should explicitly
		// re-enable each entry so games don't silently re-list on the
		// lobby every time the app launches.  We still read the key
		// for forward-compat but discard the value.
		(void)key.getBool(knEn, false);
		o.enabled = false;

		// Machine preset — clamp to valid range; default XLXE_NTSC on
		// missing/corrupt.
		int presetInt = key.getInt(knPreset, (int)MachinePreset::XLXE_NTSC);
		if (presetInt < 0 || presetInt > (int)kMachinePresetMax)
			presetInt = (int)MachinePreset::XLXE_NTSC;
		o.preset = (MachinePreset)presetInt;

		// Drop obviously-invalid slots (no path or no name).  A fresh
		// id is generated by the caller when the user adds a game,
		// so we also accept an empty id here and fix it up.
		if (o.gamePath.empty() || o.gameName.empty()) continue;
		if (o.id.empty())       o.id = GenerateHostedGameId();

		g_state.hostedGames.push_back(std::move(o));
	}
}

// Mirror of LoadOffers — writes the current hostedGames vector to registry.
static void SaveOffers(VDRegistryAppKey& key) {
	// First, strip any stale Offer<N>_* keys left over from a previous
	// save with a larger N.  We cap at kMaxHostedGames + some slack.
	const int kScan = (int)State::kMaxHostedGames + 4;
	for (int i = 0; i < kScan; ++i) {
		char knId[16], knPath[16], knName[16], knArt[16],
		     knPriv[16], knCode[16], knEn[16], knPreset[16];
		std::snprintf(knId,     sizeof knId,     "Game%d_id",      i);
		std::snprintf(knPath,   sizeof knPath,   "Game%d_path",    i);
		std::snprintf(knName,   sizeof knName,   "Game%d_name",    i);
		std::snprintf(knArt,    sizeof knArt,    "Game%d_art",     i);
		std::snprintf(knPriv,   sizeof knPriv,   "Game%d_private", i);
		std::snprintf(knCode,   sizeof knCode,   "Game%d_code",    i);
		std::snprintf(knEn,     sizeof knEn,     "Game%d_enabled", i);
		std::snprintf(knPreset, sizeof knPreset, "Game%d_preset",  i);
		key.removeValue(knId);
		key.removeValue(knPath);
		key.removeValue(knName);
		key.removeValue(knArt);
		key.removeValue(knPriv);
		key.removeValue(knCode);
		key.removeValue(knEn);
		key.removeValue(knPreset);
	}

	int n = (int)g_state.hostedGames.size();
	if ((size_t)n > State::kMaxHostedGames) n = (int)State::kMaxHostedGames;
	key.setInt("GameCount", n);
	for (int i = 0; i < n; ++i) {
		const HostedGame& o = g_state.hostedGames[i];
		char knId[16], knPath[16], knName[16], knArt[16],
		     knPriv[16], knCode[16], knEn[16], knPreset[16];
		std::snprintf(knId,     sizeof knId,     "Game%d_id",      i);
		std::snprintf(knPath,   sizeof knPath,   "Game%d_path",    i);
		std::snprintf(knName,   sizeof knName,   "Game%d_name",    i);
		std::snprintf(knArt,    sizeof knArt,    "Game%d_art",     i);
		std::snprintf(knPriv,   sizeof knPriv,   "Game%d_private", i);
		std::snprintf(knCode,   sizeof knCode,   "Game%d_code",    i);
		std::snprintf(knEn,     sizeof knEn,     "Game%d_enabled", i);
		std::snprintf(knPreset, sizeof knPreset, "Game%d_preset",  i);
		key.setString(knId,     o.id.c_str());
		key.setString(knPath,   o.gamePath.c_str());
		key.setString(knName,   o.gameName.c_str());
		key.setString(knArt,    o.cartArtHash.c_str());
		key.setBool  (knPriv,   o.isPrivate);
		key.setString(knCode,   o.entryCode.c_str());
		key.setBool  (knEn,     o.enabled);
		key.setInt   (knPreset, (int)o.preset);
	}
}

const char *MachinePresetLabel(MachinePreset p) {
	switch (p) {
		case MachinePreset::XLXE_PAL:  return "XL/XE (PAL)";
		case MachinePreset::XLXE_NTSC: return "XL/XE (NTSC)";
		case MachinePreset::A5200:     return "Atari 5200 (NTSC)";
	}
	return "(unknown)";
}

HostedGame* FindHostedGame(const std::string& id) {
	if (id.empty()) return nullptr;
	for (auto& o : g_state.hostedGames)
		if (o.id == id) return &o;
	return nullptr;
}

std::string GenerateHostedGameId() {
	char buf[17];
	for (int i = 0; i < 16; ++i) {
		uint32_t r = NextRand();
		static const char hex[] = "0123456789abcdef";
		buf[i] = hex[r & 0xF];
	}
	buf[16] = 0;
	return std::string(buf, 16);
}

void Initialize() {
	if (g_initialized) return;
	g_initialized = true;

	VDRegistryAppKey key("Netplay", true);

	// Nickname.
	VDStringA handle;
	if (key.getString("Handle", handle)) {
		g_state.prefs.nickname.assign(handle.c_str(), handle.size());
	}
	g_state.prefs.isAnonymous     = key.getBool("Anonymous", false);
	g_state.prefs.acceptMode      = (AcceptMode)key.getInt("AcceptMode",
		(int)AcceptMode::AutoAccept);
	g_state.prefs.notif.flashWindow  = key.getBool("NotifyFlash", true);
	g_state.prefs.notif.systemNotify = key.getBool("NotifySystem", true);
	g_state.prefs.notif.playChime    = key.getBool("NotifyChime", true);
	g_state.prefs.defaultInputDelayLan      = key.getInt("InputDelayLan", 3);
	g_state.prefs.defaultInputDelayInternet = key.getInt("InputDelayNet", 4);
	g_state.prefs.focusOnAttention = key.getBool("FocusOnAttention", false);
	g_state.prefs.advancedManualIp = key.getBool("AdvancedManualIp", false);

	VDStringA code;
	if (key.getString("LastEntryCode", code)) {
		g_state.prefs.lastEntryCode.assign(code.c_str(), code.size());
	}

	int lastPreset = key.getInt("LastAddPreset",
		(int)MachinePreset::XLXE_NTSC);
	if (lastPreset < 0 || lastPreset > (int)kMachinePresetMax)
		lastPreset = (int)MachinePreset::XLXE_NTSC;
	g_state.prefs.lastAddPreset = (MachinePreset)lastPreset;

	// Clamp values that may have come from a corrupted registry write.
	if (g_state.prefs.defaultInputDelayLan < 1)   g_state.prefs.defaultInputDelayLan = 3;
	if (g_state.prefs.defaultInputDelayLan > 10)  g_state.prefs.defaultInputDelayLan = 10;
	if (g_state.prefs.defaultInputDelayInternet < 1)  g_state.prefs.defaultInputDelayInternet = 4;
	if (g_state.prefs.defaultInputDelayInternet > 10) g_state.prefs.defaultInputDelayInternet = 10;
	if ((int)g_state.prefs.acceptMode < 0 || (int)g_state.prefs.acceptMode > 2)
		g_state.prefs.acceptMode = AcceptMode::AutoAccept;

	LoadOffers(key);
}

void SaveToRegistry() {
	VDRegistryAppKey key("Netplay", true);
	key.setString("Handle",           g_state.prefs.nickname.c_str());
	key.setBool  ("Anonymous",        g_state.prefs.isAnonymous);
	key.setInt   ("AcceptMode",       (int)g_state.prefs.acceptMode);
	key.setBool  ("NotifyFlash",      g_state.prefs.notif.flashWindow);
	key.setBool  ("NotifySystem",     g_state.prefs.notif.systemNotify);
	key.setBool  ("NotifyChime",      g_state.prefs.notif.playChime);
	key.setInt   ("InputDelayLan",    g_state.prefs.defaultInputDelayLan);
	key.setInt   ("InputDelayNet",    g_state.prefs.defaultInputDelayInternet);
	key.setBool  ("FocusOnAttention", g_state.prefs.focusOnAttention);
	key.setBool  ("AdvancedManualIp", g_state.prefs.advancedManualIp);
	key.setString("LastEntryCode",    g_state.prefs.lastEntryCode.c_str());
	key.setInt   ("LastAddPreset",    (int)g_state.prefs.lastAddPreset);

	SaveOffers(key);
}

void Shutdown() {
	if (g_initialized) SaveToRegistry();
	g_state = State{};
	g_resolvedCache.clear();
	g_initialized = false;
}

void Navigate(Screen next) {
	if (next == Screen::Closed) {
		g_state.backStack.clear();
		g_state.screen = Screen::Closed;
		return;
	}
	if (g_state.screen != Screen::Closed)
		g_state.backStack.push_back(g_state.screen);
	g_state.screen = next;
}

bool Back() {
	if (g_state.backStack.empty()) {
		g_state.screen = Screen::Closed;
		return false;
	}
	g_state.screen = g_state.backStack.back();
	g_state.backStack.pop_back();
	return true;
}

} // namespace ATNetplayUI
